// src/app/angular-patterns-package/src/certificate-service/pages/identity-mobile-otp/identity-mobile-otp.component.ts
import { Component, ChangeDetectionStrategy, ElementRef, ViewChildren, QueryList } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ServiceHeaderComponent } from '../../../services/components/service-header/service-header.component';
import { ServiceFooterComponent } from '../../../services/components/service-footer/service-footer.component';

@Component({
  selector: 'identity-mobile-otp-page',
  standalone: true,
  imports: [CommonModule, FormsModule, ServiceHeaderComponent, ServiceFooterComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="mo">
      <div class="mo-tricolor" aria-hidden="true"></div>
      <header class="mo-gov">
        <span class="mo-gov__icon" aria-hidden="true">🛡️</span>
        <div><div class="mo-gov__title">Government of India</div><div class="mo-gov__sub">Unified Identity Service — Mobile Verification</div></div>
      </header>

      <main class="mo-main">
        <div class="mo-content">
          <div class="mo-form-col">
            <div class="mo-card">
              <div class="mo-card__icon" aria-hidden="true">📱</div>
              <h1 class="mo-card__title">Verify Your Mobile Number</h1>
              <p class="mo-card__desc">We've sent a 6-digit OTP to <strong>+91 98XXX XXXXX</strong></p>

              <div class="mo-otp-group" role="group" aria-label="Enter 6-digit OTP">
                <input *ngFor="let d of digits; let i = index"
                  #otpInput
                  class="mo-otp-input"
                  type="text"
                  inputmode="numeric"
                  maxlength="1"
                  [attr.aria-label]="'Digit ' + (i + 1)"
                  [value]="digits[i]"
                  (input)="onDigitInput($event, i)"
                  (keydown)="onKeyDown($event, i)"
                />
              </div>

              <div class="mo-timer" aria-live="polite">
                <span *ngIf="countdown > 0">Resend OTP in <strong>{{ countdown }}s</strong></span>
                <button *ngIf="countdown === 0" type="button" class="mo-resend" (click)="resendOtp()">Resend OTP</button>
              </div>

              <button type="button" class="mo-btn mo-btn--primary" [disabled]="!isComplete" (click)="verify()">Verify &amp; Continue</button>

              <div class="mo-trouble">
                <h3>OTP Not Received?</h3>
                <ul>
                  <li>Check if your mobile number is correct</li>
                  <li>Ensure your phone has network coverage</li>
                  <li>Check your SMS inbox and spam folder</li>
                  <li>Wait a few moments and try resending</li>
                </ul>
              </div>

              <div class="mo-security">🔒 Never share your OTP with anyone. Government officials will never ask for your OTP.</div>

              <div class="mo-alt">
                <a href="/reference-service/certificate/identity/email-otp">Try Email OTP instead →</a>
              </div>
            </div>
          </div>

          <aside class="mo-sidebar">
            <div class="mo-panel">
              <h2 class="mo-panel__title">Design Annotations</h2>
              <ul class="mo-annotations">
                <li>Auto-advance on digit entry</li>
                <li>Backspace returns to previous field</li>
                <li>Countdown timer prevents OTP spam</li>
                <li>Numeric inputmode for mobile keyboards</li>
                <li>ARIA labels for each digit input</li>
              </ul>
            </div>
            <div class="mo-panel">
              <h2 class="mo-panel__title">OTP Flow</h2>
              <ol class="mo-steps">
                <li>OTP sent to registered mobile</li>
                <li class="mo-step--active">User enters 6-digit code</li>
                <li>System verifies OTP</li>
                <li>Proceed to next step</li>
              </ol>
            </div>
            <div class="mo-panel">
              <h2 class="mo-panel__title">Help</h2>
              <p class="mo-panel__text">📞 1800-111-555 (Toll Free)</p>
              <p class="mo-panel__text">Mon–Sat, 9 AM – 6 PM IST</p>
            </div>
          </aside>
        </div>
      </main>

      <ux4g-service-footer leftText="Unified Identity Service • Government of India" rightText="Mobile OTP Verification"></ux4g-service-footer>
    </div>
  `,
  styles: [`
    .mo { min-height: 100vh; background: var(--ux4g-svc-bg-muted, #f8fafc); font-family: system-ui, sans-serif; color: var(--ux4g-svc-fg, #0f172a); }
    .mo-tricolor { height: 4px; background: linear-gradient(to right, #ff9933 33%, #fff 33%, #fff 66%, #138808 66%); }
    .mo-gov { display: flex; align-items: center; gap: 0.75rem; padding: 1rem 2rem; background: var(--ux4g-svc-bg, #fff); border-bottom: 2px solid var(--ux4g-svc-border, #e2e8f0); }
    .mo-gov__icon { font-size: 1.75rem; }
    .mo-gov__title { font-weight: 700; font-size: 1rem; }
    .mo-gov__sub { font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); }
    .mo-main { max-width: 1200px; margin: 0 auto; padding: 2rem 1.5rem; }
    .mo-content { display: grid; grid-template-columns: 2fr 1fr; gap: 2rem; }
    .mo-form-col { max-width: 560px; }
    .mo-card { background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; padding: 2rem; text-align: center; }
    .mo-card__icon { font-size: 3rem; margin-bottom: 0.5rem; }
    .mo-card__title { font-size: 1.5rem; font-weight: 800; margin: 0 0 0.25rem; }
    .mo-card__desc { font-size: 0.875rem; color: var(--ux4g-svc-fg-muted, #64748b); margin: 0 0 2rem; }
    .mo-otp-group { display: flex; justify-content: center; gap: 0.75rem; margin-bottom: 1.5rem; }
    .mo-otp-input { width: 3rem; height: 3.5rem; text-align: center; font-size: 1.5rem; font-weight: 700; border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; }
    .mo-otp-input:focus { border-color: var(--ux4g-svc-primary, #4f46e5); outline: none; }
    .mo-timer { font-size: 0.875rem; color: var(--ux4g-svc-fg-muted, #64748b); margin-bottom: 1.5rem; }
    .mo-resend { background: none; border: none; color: var(--ux4g-svc-primary, #4f46e5); font-weight: 700; font-size: 0.875rem; cursor: pointer; text-decoration: underline; }
    .mo-btn { width: 100%; padding: 0.75rem; font-size: 0.875rem; font-weight: 700; border-radius: 0.375rem; border: none; cursor: pointer; }
    .mo-btn--primary { background: var(--ux4g-svc-primary, #4f46e5); color: #fff; }
    .mo-btn:disabled { background: #9ca3af; cursor: not-allowed; }
    .mo-trouble { text-align: left; background: var(--ux4g-svc-bg-muted, #f8fafc); border: 1px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.375rem; padding: 1rem; margin-top: 1.5rem; }
    .mo-trouble h3 { font-size: 0.875rem; font-weight: 700; margin: 0 0 0.5rem; }
    .mo-trouble ul { margin: 0; padding-left: 1.25rem; font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); line-height: 1.8; }
    .mo-security { background: #fef3c7; border: 1px solid #fbbf24; border-radius: 0.375rem; padding: 0.75rem; font-size: 0.75rem; margin-top: 1rem; }
    .mo-alt { margin-top: 1rem; }
    .mo-alt a { font-size: 0.8125rem; color: var(--ux4g-svc-primary, #4f46e5); text-decoration: none; font-weight: 600; }
    .mo-sidebar { display: flex; flex-direction: column; gap: 1rem; }
    .mo-panel { background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; padding: 1.25rem; }
    .mo-panel__title { font-size: 0.875rem; font-weight: 700; margin: 0 0 0.75rem; }
    .mo-panel__text { font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); margin: 0 0 0.25rem; }
    .mo-annotations { margin: 0; padding-left: 1.25rem; font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); line-height: 1.8; }
    .mo-steps { margin: 0; padding-left: 1.25rem; font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); line-height: 2; }
    .mo-step--active { color: var(--ux4g-svc-primary, #4f46e5); font-weight: 700; }
    @media (max-width: 768px) {
      .mo-content { grid-template-columns: 1fr; }
      .mo-form-col { max-width: 100%; }
      .mo-otp-input { width: 2.5rem; height: 3rem; font-size: 1.25rem; }
    }
  `],
})
export class IdentityMobileOtpComponent {
  @ViewChildren('otpInput') otpInputs!: QueryList<ElementRef>;
  digits: string[] = ['', '', '', '', '', ''];
  countdown = 30;
  private timer: any;

  get isComplete(): boolean { return this.digits.every(d => d.length === 1); }

  ngOnInit() { this.startTimer(); }
  ngOnDestroy() { clearInterval(this.timer); }

  startTimer() {
    this.countdown = 30;
    clearInterval(this.timer);
    this.timer = setInterval(() => { if (this.countdown > 0) this.countdown--; else clearInterval(this.timer); }, 1000);
  }

  onDigitInput(event: Event, index: number) {
    const input = event.target as HTMLInputElement;
    const val = input.value.replace(/\D/g, '');
    this.digits[index] = val.charAt(0) || '';
    input.value = this.digits[index];
    if (val && index < 5) {
      const inputs = this.otpInputs.toArray();
      inputs[index + 1]?.nativeElement.focus();
    }
  }

  onKeyDown(event: KeyboardEvent, index: number) {
    if (event.key === 'Backspace' && !this.digits[index] && index > 0) {
      const inputs = this.otpInputs.toArray();
      inputs[index - 1]?.nativeElement.focus();
    }
  }

  resendOtp() { this.digits = ['', '', '', '', '', '']; this.startTimer(); }
  verify() { if (this.isComplete) { /* navigate */ } }
}

// src/app/pages/IdentityMobileOTP.tsx
import { Link } from "react-router";
import { ArrowLeft, Shield, Smartphone, Check, RefreshCw, HelpCircle, CheckCircle, Info, Clock } from "lucide-react";
import { useState, useEffect, useRef } from "react";

export default function IdentityMobileOTP() {
  const [otp, setOtp] = useState(["", "", "", "", "", ""]);
  const [countdown, setCountdown] = useState(30);
  const [canResend, setCanResend] = useState(false);
  const inputRefs = useRef<(HTMLInputElement | null)[]>([]);

  useEffect(() => {
    if (countdown > 0) {
      const timer = setTimeout(() => setCountdown(countdown - 1), 1000);
      return () => clearTimeout(timer);
    } else {
      setCanResend(true);
    }
  }, [countdown]);

  const handleOtpChange = (index: number, value: string) => {
    if (value.length <= 1 && /^\d*$/.test(value)) {
      const newOtp = [...otp];
      newOtp[index] = value;
      setOtp(newOtp);

      // Auto-advance to next input
      if (value && index < 5) {
        inputRefs.current[index + 1]?.focus();
      }
    }
  };

  const handleKeyDown = (index: number, e: React.KeyboardEvent) => {
    if (e.key === "Backspace" && !otp[index] && index > 0) {
      inputRefs.current[index - 1]?.focus();
    }
  };

  const handlePaste = (e: React.ClipboardEvent) => {
    e.preventDefault();
    const pastedData = e.clipboardData.getData("text").slice(0, 6);
    if (/^\d+$/.test(pastedData)) {
      const newOtp = pastedData.split("");
      while (newOtp.length < 6) newOtp.push("");
      setOtp(newOtp);
    }
  };

  const handleResend = () => {
    setCountdown(30);
    setCanResend(false);
    setOtp(["", "", "", "", "", ""]);
    inputRefs.current[0]?.focus();
  };

  const isOtpComplete = otp.every(digit => digit !== "");

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation Bar */}
      <nav className="bg-card border-b-2 border-border">
        <div className="max-w-[1400px] mx-auto px-8 py-4 flex items-center justify-between">
          <Link to="/patterns/identity" className="flex items-center gap-2 text-muted-foreground hover:text-primary">
            <ArrowLeft size={20} />
            <span className="font-medium">Back to Identity Patterns</span>
          </Link>
          <div className="text-sm text-muted-foreground">
            <span className="font-bold">Flow:</span> Mobile OTP Verification
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-[1400px] mx-auto px-8 py-12">
        <div className="grid grid-cols-12 gap-8">
          
          {/* Prototype View - 8 columns */}
          <div className="col-span-8">
            <div className="bg-card border-2 border-border rounded-lg overflow-hidden shadow-lg">
              {/* Tricolor Header */}
              <div className="bg-gradient-to-r from-orange-500 via-white to-green-500 h-2"></div>
              
              {/* Government Header */}
              <div className="bg-card border-b-2 border-border px-8 py-6">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-primary rounded flex items-center justify-center">
                    <Shield size={24} className="text-white" />
                  </div>
                  <div>
                    <div className="font-bold text-lg text-foreground">Digital India Portal</div>
                    <div className="text-sm text-muted-foreground">Government of India</div>
                  </div>
                </div>
              </div>

              {/* Form Content */}
              <div className="px-12 py-10">
                <div className="max-w-xl mx-auto">
                  {/* Icon and Title */}
                  <div className="text-center mb-8">
                    <div className="inline-flex items-center justify-center w-20 h-20 bg-blue-100 border-2 border-blue-300 rounded-full mb-4">
                      <Smartphone size={40} className="text-blue-600" />
                    </div>
                    <h1 className="text-3xl font-bold text-foreground mb-3">Verify Your Mobile Number</h1>
                    <p className="text-muted-foreground">
                      We've sent a 6-digit OTP to
                    </p>
                    <p className="text-lg font-bold text-foreground mt-2">+91 98765 43210</p>
                    <button className="text-sm text-primary font-bold hover:underline mt-2">
                      Change number
                    </button>
                  </div>

                  {/* OTP Input */}
                  <div className="mb-8">
                    <label className="block text-sm font-bold text-foreground mb-4 text-center">
                      Enter OTP <span className="text-red-600">*</span>
                    </label>
                    <div className="flex gap-3 justify-center" onPaste={handlePaste}>
                      {otp.map((digit, index) => (
                        <input
                          key={index}
                          ref={(el) => (inputRefs.current[index] = el)}
                          type="text"
                          inputMode="numeric"
                          maxLength={1}
                          value={digit}
                          onChange={(e) => handleOtpChange(index, e.target.value)}
                          onKeyDown={(e) => handleKeyDown(index, e)}
                          className="w-14 h-16 text-center text-2xl font-bold border-2 border-border rounded-lg focus:border-primary focus:outline-none text-foreground"
                          aria-label={`OTP digit ${index + 1}`}
                        />
                      ))}
                    </div>
                    <div className="text-sm text-muted-foreground text-center mt-3">
                      Paste OTP if copied from SMS
                    </div>
                  </div>

                  {/* Countdown Timer */}
                  <div className="mb-6">
                    {!canResend ? (
                      <div className="bg-blue-50 border-2 border-blue-200 rounded-lg p-4 text-center">
                        <div className="flex items-center justify-center gap-2 text-blue-700">
                          <Clock size={20} />
                          <span className="font-bold">
                            Resend OTP in {countdown} seconds
                          </span>
                        </div>
                      </div>
                    ) : (
                      <div className="text-center">
                        <p className="text-sm text-muted-foreground mb-3">Didn't receive the OTP?</p>
                        <button
                          onClick={handleResend}
                          className="inline-flex items-center gap-2 px-6 py-3 border-2 border-primary text-primary font-bold rounded-lg hover:bg-blue-50 transition-colors"
                        >
                          <RefreshCw size={18} />
                          Resend OTP
                        </button>
                      </div>
                    )}
                  </div>

                  {/* Verify Button */}
                  <div className="mb-6">
                    <button
                      disabled={!isOtpComplete}
                      className={`w-full px-8 py-5 font-bold rounded-lg text-lg transition-colors ${
                        isOtpComplete
                          ? 'bg-primary text-white hover:opacity-90'
                          : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                      }`}
                    >
                      Verify & Continue
                    </button>
                  </div>

                  {/* Info Boxes */}
                  <div className="space-y-4">
                    {/* OTP Not Received */}
                    <div className="bg-yellow-50 border-l-4 border-yellow-600 p-4 rounded-r-lg">
                      <div className="flex items-start gap-3">
                        <Info size={20} className="text-yellow-600 flex-shrink-0 mt-0.5" />
                        <div>
                          <div className="font-bold text-sm text-foreground mb-1">OTP Not Received?</div>
                          <ul className="text-sm text-muted-foreground space-y-1">
                            <li>• Check your SMS inbox (OTP usually arrives within 30 seconds)</li>
                            <li>• Ensure your mobile has network coverage</li>
                            <li>• Try resending OTP after countdown completes</li>
                            <li>• Contact helpline if issue persists: <strong>1800-XXX-XXXX</strong></li>
                          </ul>
                        </div>
                      </div>
                    </div>

                    {/* Security Notice */}
                    <div className="bg-green-50 border-l-4 border-green-600 p-4 rounded-r-lg">
                      <div className="flex items-start gap-3">
                        <Shield size={20} className="text-green-600 flex-shrink-0 mt-0.5" />
                        <div>
                          <div className="font-bold text-sm text-foreground mb-1">Security Reminder</div>
                          <div className="text-sm text-muted-foreground">
                            Never share your OTP with anyone. Government officials will never ask for your OTP 
                            over phone, email, or SMS.
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Alternative Verification */}
                  <div className="mt-8 text-center text-sm text-muted-foreground">
                    Having trouble with mobile OTP?{" "}
                    <Link to="/patterns/identity/otp-verification" className="text-primary font-bold hover:underline">
                      Try Email OTP instead
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Documentation Sidebar - 4 columns */}
          <div className="col-span-4 space-y-6 sticky top-24 self-start">
            <AnnotationPanel />
            <FlowNavigation />
            <HelpPanel />
          </div>

        </div>
      </main>
    </div>
  );
}

function AnnotationPanel() {
  return (
    <div className="border-2 border-blue-200 rounded-lg overflow-hidden bg-blue-50">
      <div className="bg-blue-100 border-b-2 border-blue-200 px-4 py-3">
        <h3 className="font-bold text-foreground text-sm">Design Annotations</h3>
      </div>
      <div className="p-4">
        <ul className="space-y-2 text-sm text-muted-foreground">
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>6 individual inputs with auto-advance on entry</span>
          </li>
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>Paste support for codes copied from SMS</span>
          </li>
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>30-second countdown prevents spam resend</span>
          </li>
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>Mobile number displayed for confirmation</span>
          </li>
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>Clear troubleshooting guidance provided</span>
          </li>
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>Fallback to email OTP if mobile fails</span>
          </li>
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>Security warning about OTP sharing</span>
          </li>
        </ul>
      </div>
    </div>
  );
}

function FlowNavigation() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3">
        <h3 className="font-bold text-foreground text-sm">OTP Verification Flow</h3>
      </div>
      <div className="p-4">
        <div className="space-y-3 text-sm">
          <FlowStep number="1" label="Mobile Number Entered" completed />
          <FlowStep number="2" label="OTP Sent" completed />
          <FlowStep number="3" label="Enter OTP" active />
          <FlowStep number="4" label="Verification Complete" />
        </div>
      </div>
    </div>
  );
}

function FlowStep({ number, label, active = false, completed = false }: { number: string; label: string; active?: boolean; completed?: boolean }) {
  return (
    <div className={`flex items-center gap-3 p-3 rounded ${
      active ? 'bg-blue-100 border-2 border-blue-300' : 
      completed ? 'bg-green-50 border-2 border-green-300' :
      'bg-background border-2 border-border'
    }`}>
      <div className={`w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm ${
        active ? 'bg-primary text-white' : 
        completed ? 'bg-green-600 text-white' :
        'bg-gray-300 text-muted-foreground'
      }`}>
        {completed ? <Check size={16} /> : number}
      </div>
      <span className={`font-medium ${active || completed ? 'text-foreground' : 'text-muted-foreground'}`}>{label}</span>
    </div>
  );
}

function HelpPanel() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3 flex items-center gap-2">
        <HelpCircle size={16} className="text-muted-foreground" />
        <h3 className="font-bold text-foreground text-sm">Need Help?</h3>
      </div>
      <div className="p-4 space-y-4 text-sm text-muted-foreground">
        <div>
          <div className="font-bold text-foreground mb-1">Helpline</div>
          <div className="text-primary font-bold">1800-XXX-XXXX</div>
          <div className="text-xs text-muted-foreground">Mon-Sat, 9 AM - 6 PM</div>
        </div>
        <div>
          <div className="font-bold text-foreground mb-1">Common Issues</div>
          <ul className="space-y-1 text-xs">
            <li>• OTP not received? Wait 30 sec, then resend</li>
            <li>• Network issues? <Link to="/patterns/identity/otp-verification" className="text-primary hover:underline">Try email OTP</Link></li>
            <li>• Wrong number? Go back and change</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
