// src/app/angular-patterns-package/src/certificate-service/pages/identity-aadhaar/identity-aadhaar.component.ts
import { Component, ChangeDetectionStrategy, ElementRef, ViewChildren, QueryList } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ServiceHeaderComponent } from '../../../services/components/service-header/service-header.component';
import { ServiceFooterComponent } from '../../../services/components/service-footer/service-footer.component';

@Component({
  selector: 'identity-aadhaar-page',
  standalone: true,
  imports: [CommonModule, FormsModule, ServiceHeaderComponent, ServiceFooterComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="aa">
      <div class="aa-tricolor" aria-hidden="true"></div>
      <header class="aa-gov">
        <span class="aa-gov__icon" aria-hidden="true">🛡️</span>
        <div><div class="aa-gov__title">Government of India</div><div class="aa-gov__sub">Unified Identity Service — Aadhaar Authentication</div></div>
      </header>

      <main class="aa-main">
        <div class="aa-content">
          <div class="aa-form-col">
            <!-- Progress -->
            <div class="aa-progress" role="navigation" aria-label="Aadhaar authentication steps">
              <div *ngFor="let s of stepLabels; let i = index" class="aa-step" [class.aa-step--active]="step === i + 1" [class.aa-step--done]="step > i + 1">
                <div class="aa-step__num">{{ step > i + 1 ? '✓' : i + 1 }}</div>
                <div class="aa-step__label">{{ s }}</div>
              </div>
            </div>

            <!-- Step 1: Consent -->
            <div class="aa-card" *ngIf="step === 1">
              <div class="aa-card__icon" aria-hidden="true">🆔</div>
              <h1 class="aa-card__title">Aadhaar Authentication</h1>
              <p class="aa-card__desc">This service uses UIDAI's Aadhaar authentication to verify your identity securely.</p>

              <div class="aa-consent-list">
                <h3>By proceeding, you consent to:</h3>
                <ul>
                  <li *ngFor="let c of consentPoints">{{ c }}</li>
                </ul>
              </div>

              <label class="aa-checkbox">
                <input type="checkbox" [(ngModel)]="consentGiven" name="consent" />
                <span>I have read and agree to the above terms for Aadhaar authentication</span>
              </label>

              <button type="button" class="aa-btn aa-btn--primary" [disabled]="!consentGiven" (click)="step = 2">Proceed to Aadhaar Entry</button>
            </div>

            <!-- Step 2: Enter Aadhaar -->
            <div class="aa-card" *ngIf="step === 2">
              <h1 class="aa-card__title">Enter Your Aadhaar Number</h1>
              <p class="aa-card__desc">Enter your 12-digit Aadhaar number to receive an OTP.</p>

              <div class="aa-field">
                <label class="aa-label" for="aadhaar">Aadhaar Number <span class="aa-req">*</span></label>
                <input id="aadhaar" class="aa-input aa-input--aadhaar" [type]="showAadhaar ? 'text' : 'password'" [(ngModel)]="aadhaarNumber" name="aadhaar" placeholder="XXXX XXXX XXXX" maxlength="12" inputmode="numeric" />
                <button type="button" class="aa-toggle" (click)="showAadhaar = !showAadhaar" [attr.aria-label]="showAadhaar ? 'Hide Aadhaar' : 'Show Aadhaar'">
                  {{ showAadhaar ? '🙈 Hide' : '👁️ Show' }}
                </button>
              </div>

              <div class="aa-security-notice">🔒 Your Aadhaar number is encrypted and never stored. Never share your Aadhaar with unauthorized persons.</div>

              <button type="button" class="aa-btn aa-btn--primary" [disabled]="aadhaarNumber.length !== 12" (click)="step = 3">Send OTP to Aadhaar-linked Mobile</button>
            </div>

            <!-- Step 3: OTP -->
            <div class="aa-card" *ngIf="step === 3">
              <h1 class="aa-card__title">Enter Aadhaar OTP</h1>
              <p class="aa-card__desc">OTP sent to mobile linked with Aadhaar <strong>XXXX XXXX {{ aadhaarNumber.slice(-4) || '1234' }}</strong></p>

              <div class="aa-otp-group" role="group" aria-label="Enter 6-digit OTP">
                <input *ngFor="let d of otpDigits; let i = index"
                  #otpInput
                  class="aa-otp-input"
                  type="text"
                  inputmode="numeric"
                  maxlength="1"
                  [attr.aria-label]="'Digit ' + (i + 1)"
                  [value]="otpDigits[i]"
                  (input)="onDigitInput($event, i)"
                  (keydown)="onKeyDown($event, i)"
                />
              </div>

              <div class="aa-resend-row">
                <button type="button" class="aa-link" (click)="resendOtp()">Resend OTP</button>
              </div>

              <button type="button" class="aa-btn aa-btn--primary" [disabled]="!otpComplete" (click)="step = 4">Verify Aadhaar</button>
            </div>

            <!-- Step 4: Success -->
            <div class="aa-card aa-card--success" *ngIf="step === 4">
              <div class="aa-success-icon" aria-hidden="true">✅</div>
              <h1 class="aa-card__title">Aadhaar Verified Successfully</h1>
              <p class="aa-card__desc">Your identity has been verified through UIDAI.</p>

              <div class="aa-verified">
                <div class="aa-verified__row"><span class="aa-verified__label">Name</span><span>Priya Sharma</span></div>
                <div class="aa-verified__row"><span class="aa-verified__label">Aadhaar</span><span>XXXX XXXX {{ aadhaarNumber.slice(-4) || '1234' }}</span></div>
                <div class="aa-verified__row"><span class="aa-verified__label">Status</span><span class="aa-badge aa-badge--green">UIDAI Verified</span></div>
                <div class="aa-verified__row"><span class="aa-verified__label">Timestamp</span><span>{{ verifiedTimestamp }}</span></div>
              </div>

              <button type="button" class="aa-btn aa-btn--primary" (click)="onContinue()">Continue to Application</button>
            </div>
          </div>

          <aside class="aa-sidebar">
            <div class="aa-panel"><h2 class="aa-panel__title">Pattern Info</h2><p class="aa-panel__text">Aadhaar-based authentication using UIDAI's OTP service. Provides strong identity verification for government services.</p></div>
            <div class="aa-panel"><h2 class="aa-panel__title">Consent Requirements</h2>
              <ul class="aa-list"><li>Explicit user consent required by law</li><li>Purpose limitation must be stated</li><li>Data minimization principle applies</li><li>Consent can be withdrawn</li></ul>
            </div>
            <div class="aa-panel"><h2 class="aa-panel__title">Security Notes</h2>
              <ul class="aa-list"><li>Aadhaar number is masked after entry</li><li>OTP valid for 10 minutes only</li><li>End-to-end encryption with UIDAI</li><li>No biometric data collected</li></ul>
            </div>
            <div class="aa-panel"><h2 class="aa-panel__title">Legal Compliance</h2>
              <ul class="aa-list"><li>Aadhaar Act, 2016 compliant</li><li>UIDAI authentication guidelines</li><li>IT Act, 2000 data protection</li><li>Supreme Court privacy ruling adherence</li></ul>
            </div>
          </aside>
        </div>
      </main>

      <ux4g-service-footer leftText="Unified Identity Service • Government of India" rightText="Aadhaar Authentication"></ux4g-service-footer>
    </div>
  `,
  styles: [`
    .aa { min-height: 100vh; background: var(--ux4g-svc-bg-muted, #f8fafc); font-family: system-ui, sans-serif; color: var(--ux4g-svc-fg, #0f172a); }
    .aa-tricolor { height: 4px; background: linear-gradient(to right, #ff9933 33%, #fff 33%, #fff 66%, #138808 66%); }
    .aa-gov { display: flex; align-items: center; gap: 0.75rem; padding: 1rem 2rem; background: var(--ux4g-svc-bg, #fff); border-bottom: 2px solid var(--ux4g-svc-border, #e2e8f0); }
    .aa-gov__icon { font-size: 1.75rem; }
    .aa-gov__title { font-weight: 700; font-size: 1rem; }
    .aa-gov__sub { font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); }
    .aa-main { max-width: 1200px; margin: 0 auto; padding: 2rem 1.5rem; }
    .aa-content { display: grid; grid-template-columns: 2fr 1fr; gap: 2rem; }
    .aa-form-col { max-width: 600px; }
    .aa-progress { display: flex; gap: 0.5rem; margin-bottom: 1.5rem; }
    .aa-step { display: flex; align-items: center; gap: 0.375rem; flex: 1; padding: 0.625rem; background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.375rem; font-size: 0.75rem; color: var(--ux4g-svc-fg-muted, #64748b); }
    .aa-step--active { border-color: var(--ux4g-svc-primary, #4f46e5); color: var(--ux4g-svc-primary, #4f46e5); font-weight: 700; }
    .aa-step--done { border-color: #16a34a; color: #16a34a; }
    .aa-step__num { width: 1.5rem; height: 1.5rem; border-radius: 50%; background: var(--ux4g-svc-border, #e2e8f0); display: flex; align-items: center; justify-content: center; font-size: 0.6875rem; font-weight: 700; flex-shrink: 0; }
    .aa-step--active .aa-step__num { background: var(--ux4g-svc-primary, #4f46e5); color: #fff; }
    .aa-step--done .aa-step__num { background: #16a34a; color: #fff; }
    .aa-card { background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; padding: 2rem; }
    .aa-card--success { text-align: center; border-color: #86efac; }
    .aa-card__icon { font-size: 3rem; text-align: center; margin-bottom: 0.5rem; }
    .aa-card__title { font-size: 1.5rem; font-weight: 800; margin: 0 0 0.25rem; }
    .aa-card__desc { font-size: 0.875rem; color: var(--ux4g-svc-fg-muted, #64748b); margin: 0 0 1.5rem; }
    .aa-consent-list { background: var(--ux4g-svc-bg-muted, #f8fafc); border: 1px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.375rem; padding: 1rem 1rem 1rem 1.25rem; margin-bottom: 1.5rem; }
    .aa-consent-list h3 { font-size: 0.875rem; font-weight: 700; margin: 0 0 0.5rem; }
    .aa-consent-list ul { margin: 0; padding-left: 1.25rem; font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); line-height: 1.8; }
    .aa-checkbox { display: flex; align-items: flex-start; gap: 0.5rem; font-size: 0.8125rem; cursor: pointer; margin-bottom: 1.5rem; padding: 0.875rem; border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.375rem; }
    .aa-field { position: relative; margin-bottom: 1rem; }
    .aa-label { display: block; font-size: 0.875rem; font-weight: 700; margin-bottom: 0.375rem; }
    .aa-req { color: #dc2626; }
    .aa-input { width: 100%; padding: 0.75rem; border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.375rem; font-size: 1.125rem; font-family: monospace; letter-spacing: 0.15em; box-sizing: border-box; }
    .aa-input:focus { border-color: var(--ux4g-svc-primary, #4f46e5); outline: none; }
    .aa-toggle { position: absolute; right: 0.75rem; bottom: 0.625rem; background: none; border: none; cursor: pointer; font-size: 0.8125rem; color: var(--ux4g-svc-primary, #4f46e5); font-weight: 600; }
    .aa-security-notice { background: #fef3c7; border: 1px solid #fbbf24; border-radius: 0.375rem; padding: 0.75rem; font-size: 0.75rem; margin-bottom: 1.5rem; }
    .aa-otp-group { display: flex; justify-content: center; gap: 0.75rem; margin-bottom: 1rem; }
    .aa-otp-input { width: 3rem; height: 3.5rem; text-align: center; font-size: 1.5rem; font-weight: 700; border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; }
    .aa-otp-input:focus { border-color: var(--ux4g-svc-primary, #4f46e5); outline: none; }
    .aa-resend-row { text-align: center; margin-bottom: 1.5rem; }
    .aa-link { background: none; border: none; color: var(--ux4g-svc-primary, #4f46e5); font-weight: 700; font-size: 0.8125rem; cursor: pointer; text-decoration: underline; }
    .aa-btn { display: block; width: 100%; padding: 0.75rem; font-size: 0.875rem; font-weight: 700; border-radius: 0.375rem; border: none; cursor: pointer; text-align: center; }
    .aa-btn--primary { background: var(--ux4g-svc-primary, #4f46e5); color: #fff; }
    .aa-btn:disabled { background: #9ca3af; cursor: not-allowed; }
    .aa-success-icon { font-size: 3rem; margin-bottom: 0.5rem; }
    .aa-verified { border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.375rem; overflow: hidden; margin-bottom: 1.5rem; text-align: left; }
    .aa-verified__row { display: flex; justify-content: space-between; padding: 0.75rem 1rem; font-size: 0.875rem; border-bottom: 1px solid var(--ux4g-svc-border, #e2e8f0); }
    .aa-verified__row:last-child { border-bottom: none; }
    .aa-verified__row:nth-child(even) { background: var(--ux4g-svc-bg-muted, #f8fafc); }
    .aa-verified__label { font-weight: 700; color: var(--ux4g-svc-fg-muted, #64748b); }
    .aa-badge { display: inline-block; padding: 0.125rem 0.5rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 700; }
    .aa-badge--green { background: #dcfce7; color: #16a34a; }
    .aa-sidebar { display: flex; flex-direction: column; gap: 1rem; }
    .aa-panel { background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; padding: 1.25rem; }
    .aa-panel__title { font-size: 0.875rem; font-weight: 700; margin: 0 0 0.75rem; }
    .aa-panel__text { font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); margin: 0; }
    .aa-list { margin: 0; padding-left: 1.25rem; font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); line-height: 1.8; }
    @media (max-width: 768px) {
      .aa-content { grid-template-columns: 1fr; }
      .aa-form-col { max-width: 100%; }
      .aa-progress { flex-wrap: wrap; }
      .aa-otp-input { width: 2.5rem; height: 3rem; font-size: 1.25rem; }
    }
  `],
})
export class IdentityAadhaarComponent {
  @ViewChildren('otpInput') otpInputs!: QueryList<ElementRef>;
  step = 1;
  stepLabels = ['Consent', 'Enter', 'OTP', 'Success'];
  consentGiven = false;
  aadhaarNumber = '';
  showAadhaar = false;
  otpDigits: string[] = ['', '', '', '', '', ''];

  consentPoints = [
    'Sharing your Aadhaar number with UIDAI for authentication',
    'Receiving an OTP on your Aadhaar-linked mobile number',
    'Verification of your identity for this government service',
    'Your Aadhaar data will not be stored beyond this session',
    'This authentication is voluntary and you may choose alternatives',
    'Data usage is governed by the Aadhaar Act, 2016',
  ];

  get otpComplete(): boolean { return this.otpDigits.every(d => d.length === 1); }

  get verifiedTimestamp(): string {
    const now = new Date();
    return now.toLocaleDateString('en-IN', { year: 'numeric', month: 'short', day: 'numeric' }) + ' ' +
           now.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
  }

  onDigitInput(event: Event, index: number) {
    const input = event.target as HTMLInputElement;
    const val = input.value.replace(/\D/g, '');
    this.otpDigits[index] = val.charAt(0) || '';
    input.value = this.otpDigits[index];
    if (val && index < 5) {
      const inputs = this.otpInputs.toArray();
      inputs[index + 1]?.nativeElement.focus();
    }
  }

  onKeyDown(event: KeyboardEvent, index: number) {
    if (event.key === 'Backspace' && !this.otpDigits[index] && index > 0) {
      const inputs = this.otpInputs.toArray();
      inputs[index - 1]?.nativeElement.focus();
    }
  }

  resendOtp() { this.otpDigits = ['', '', '', '', '', '']; }
  onContinue() { /* navigate to application */ }
}

// src/app/pages/IdentityAadhaar.tsx
import { Link } from "react-router";
import { ArrowLeft, Shield, FileText, Check, Eye, Info, HelpCircle, CheckCircle, AlertTriangle } from "lucide-react";
import { useState } from "react";

export default function IdentityAadhaar() {
  const [step, setStep] = useState<"consent" | "enter" | "otp" | "success">("consent");
  const [aadhaarNumber, setAadhaarNumber] = useState("");
  const [otp, setOtp] = useState("");
  const [consentGiven, setConsentGiven] = useState(false);

  const maskAadhaar = (num: string) => {
    if (num.length > 8) {
      return `XXXX XXXX ${num.slice(-4)}`;
    }
    return num;
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation Bar */}
      <nav className="bg-card border-b-2 border-border">
        <div className="max-w-[1400px] mx-auto px-8 py-4 flex items-center justify-between">
          <Link to="/patterns/identity" className="flex items-center gap-2 text-muted-foreground hover:text-primary">
            <ArrowLeft size={20} />
            <span className="font-medium">Back to Identity Patterns</span>
          </Link>
          <div className="text-sm text-muted-foreground">
            <span className="font-bold">Flow:</span> Aadhaar Authentication
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-[1400px] mx-auto px-8 py-12">
        <div className="grid grid-cols-12 gap-8">
          
          {/* Prototype View - 8 columns */}
          <div className="col-span-8">
            <div className="bg-card border-2 border-border rounded-lg overflow-hidden shadow-lg">
              {/* Tricolor Header */}
              <div className="bg-gradient-to-r from-orange-500 via-white to-green-500 h-2"></div>
              
              {/* Government Header */}
              <div className="bg-card border-b-2 border-border px-8 py-6">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-primary rounded flex items-center justify-center">
                    <Shield size={24} className="text-white" />
                  </div>
                  <div>
                    <div className="font-bold text-lg text-foreground">Digital India Portal</div>
                    <div className="text-sm text-muted-foreground">Government of India</div>
                  </div>
                </div>
              </div>

              {/* Progress Indicator */}
              <div className="bg-muted border-b-2 border-border px-12 py-4">
                <div className="flex items-center justify-between max-w-2xl mx-auto">
                  <ProgressStep number={1} label="Consent" active={step === "consent"} completed={step !== "consent"} />
                  <div className={`flex-1 h-0.5 mx-2 ${step !== "consent" ? 'bg-green-500' : 'bg-gray-300'}`}></div>
                  <ProgressStep number={2} label="Enter Aadhaar" active={step === "enter"} completed={step === "otp" || step === "success"} />
                  <div className={`flex-1 h-0.5 mx-2 ${step === "otp" || step === "success" ? 'bg-green-500' : 'bg-gray-300'}`}></div>
                  <ProgressStep number={3} label="Verify OTP" active={step === "otp"} completed={step === "success"} />
                  <div className={`flex-1 h-0.5 mx-2 ${step === "success" ? 'bg-green-500' : 'bg-gray-300'}`}></div>
                  <ProgressStep number={4} label="Complete" active={step === "success"} completed={false} />
                </div>
              </div>

              {/* Form Content */}
              <div className="px-12 py-10">
                <div className="max-w-2xl mx-auto">
                  
                  {/* Step 1: Consent */}
                  {step === "consent" && (
                    <div>
                      <div className="w-20 h-20 bg-indigo-100 rounded-full flex items-center justify-center mx-auto mb-6">
                        <FileText size={40} className="text-indigo-600" />
                      </div>
                      <h1 className="text-3xl font-bold text-foreground mb-3 text-center">Aadhaar Authentication Consent</h1>
                      <p className="text-muted-foreground mb-8 text-center">
                        Read and accept the terms before proceeding with Aadhaar-based authentication
                      </p>

                      <div className="p-6 bg-blue-50 dark:bg-blue-950/30 border-2 border-blue-200 dark:border-blue-800 rounded-lg mb-6">
                        <div className="flex items-start gap-3 mb-4">
                          <Info size={20} className="text-blue-600 flex-shrink-0 mt-0.5" />
                          <div className="text-sm text-muted-foreground">
                            <div className="font-bold text-foreground mb-2">What is Aadhaar Authentication?</div>
                            <p>Aadhaar authentication verifies your identity using your 12-digit Aadhaar number and OTP sent to your registered mobile number. This is a secure method approved by UIDAI (Unique Identification Authority of India).</p>
                          </div>
                        </div>
                      </div>

                      <div className="border-2 border-border rounded-lg p-6 mb-6 max-h-96 overflow-y-auto">
                        <h3 className="font-bold text-foreground mb-4">Terms and Conditions</h3>
                        <div className="space-y-4 text-sm text-muted-foreground">
                          <ConsentPoint text="I authorize the use of my Aadhaar number for authentication purposes" />
                          <ConsentPoint text="I understand that my Aadhaar details will be shared with UIDAI for verification" />
                          <ConsentPoint text="I confirm that the mobile number linked to my Aadhaar is accessible" />
                          <ConsentPoint text="I will receive an OTP on my Aadhaar-registered mobile number" />
                          <ConsentPoint text="My demographic information (name, date of birth, address) may be verified" />
                          <ConsentPoint text="This authentication complies with Aadhaar Act, 2016 and IT Act, 2000" />
                        </div>
                      </div>

                      <label className="flex items-start gap-3 p-4 border-2 border-border rounded-lg cursor-pointer hover:border-primary hover:bg-blue-50 transition-colors mb-6">
                        <input
                          type="checkbox"
                          checked={consentGiven}
                          onChange={(e) => setConsentGiven(e.target.checked)}
                          className="w-5 h-5 mt-0.5"
                        />
                        <span className="text-sm text-foreground font-medium">
                          I have read and accept the terms and conditions for Aadhaar authentication
                        </span>
                      </label>

                      <button
                        onClick={() => setStep("enter")}
                        disabled={!consentGiven}
                        className="w-full py-4 bg-primary text-white font-bold rounded-lg hover:opacity-90 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
                      >
                        Proceed to Authentication
                      </button>
                    </div>
                  )}

                  {/* Step 2: Enter Aadhaar */}
                  {step === "enter" && (
                    <div>
                      <div className="w-20 h-20 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-6">
                        <Shield size={40} className="text-primary" />
                      </div>
                      <h1 className="text-3xl font-bold text-foreground mb-3 text-center">Enter Aadhaar Number</h1>
                      <p className="text-muted-foreground mb-8 text-center">
                        Provide your 12-digit Aadhaar number for verification
                      </p>

                      <div className="mb-8">
                        <label htmlFor="aadhaar" className="block text-sm font-bold text-foreground mb-2">
                          Aadhaar Number <span className="text-red-600">*</span>
                        </label>
                        <input
                          type="text"
                          id="aadhaar"
                          value={aadhaarNumber}
                          onChange={(e) => setAadhaarNumber(e.target.value.replace(/\D/g, '').slice(0, 12))}
                          className="w-full px-4 py-4 border-2 border-border rounded-lg text-center text-2xl font-bold tracking-widest focus:border-primary focus:outline-none"
                          placeholder="XXXX XXXX XXXX"
                          maxLength={12}
                        />
                        <div className="text-sm text-muted-foreground mt-2">
                          <Info size={14} className="inline mr-1" />
                          Your Aadhaar number is encrypted and transmitted securely
                        </div>
                      </div>

                      <div className="p-6 bg-yellow-50 dark:bg-yellow-950/30 border-2 border-yellow-200 dark:border-yellow-800 rounded-lg mb-8">
                        <div className="flex items-start gap-3">
                          <AlertTriangle size={20} className="text-yellow-600 flex-shrink-0 mt-0.5" />
                          <div className="text-sm text-muted-foreground">
                            <div className="font-bold text-foreground mb-2">Security Notice</div>
                            <ul className="space-y-1">
                              <li>• Never share your Aadhaar number on unsecured websites</li>
                              <li>• Verify the URL starts with https://</li>
                              <li>• Government services never ask for Aadhaar via email/SMS</li>
                            </ul>
                          </div>
                        </div>
                      </div>

                      <button
                        onClick={() => setStep("otp")}
                        disabled={aadhaarNumber.length !== 12}
                        className="w-full py-4 bg-primary text-white font-bold rounded-lg hover:opacity-90 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
                      >
                        Send OTP
                      </button>
                    </div>
                  )}

                  {/* Step 3: OTP Verification */}
                  {step === "otp" && (
                    <div>
                      <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
                        <Shield size={40} className="text-green-600" />
                      </div>
                      <h1 className="text-3xl font-bold text-foreground mb-3 text-center">Verify OTP</h1>
                      <p className="text-muted-foreground mb-2 text-center">
                        OTP sent to mobile number linked with Aadhaar
                      </p>
                      <p className="text-lg font-bold text-foreground mb-8 text-center">
                        {maskAadhaar(aadhaarNumber)}
                      </p>

                      <div className="mb-8">
                        <label htmlFor="otp" className="block text-sm font-bold text-foreground mb-2">
                          Enter 6-Digit OTP <span className="text-red-600">*</span>
                        </label>
                        <input
                          type="text"
                          id="otp"
                          value={otp}
                          onChange={(e) => setOtp(e.target.value.replace(/\D/g, '').slice(0, 6))}
                          className="w-full px-4 py-4 border-2 border-border rounded-lg text-center text-2xl font-bold tracking-widest focus:border-primary focus:outline-none"
                          placeholder="______"
                          maxLength={6}
                        />
                        <div className="text-sm text-muted-foreground mt-2">
                          Didn't receive OTP? <button className="text-primary font-bold hover:underline">Resend</button>
                        </div>
                      </div>

                      <button
                        onClick={() => setStep("success")}
                        disabled={otp.length !== 6}
                        className="w-full py-4 bg-primary text-white font-bold rounded-lg hover:opacity-90 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
                      >
                        Verify and Authenticate
                      </button>
                    </div>
                  )}

                  {/* Step 4: Success */}
                  {step === "success" && (
                    <div className="text-center">
                      <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
                        <CheckCircle size={40} className="text-green-600" />
                      </div>
                      <h1 className="text-3xl font-bold text-foreground mb-3">Authentication Successful</h1>
                      <p className="text-muted-foreground mb-8">
                        Your identity has been verified successfully using Aadhaar
                      </p>

                      <div className="p-6 bg-green-50 dark:bg-green-950/30 border-2 border-green-200 dark:border-green-800 rounded-lg mb-8 text-left">
                        <div className="font-bold text-foreground mb-3">Verified Details</div>
                        <div className="space-y-2 text-sm text-muted-foreground">
                          <VerifiedDetail label="Name" value="As per Aadhaar" />
                          <VerifiedDetail label="Aadhaar" value={maskAadhaar(aadhaarNumber)} />
                          <VerifiedDetail label="Authentication" value="UIDAI Verified ✓" />
                          <VerifiedDetail label="Timestamp" value={new Date().toLocaleString()} />
                        </div>
                      </div>

                      <Link
                        to="/patterns/identity"
                        className="block w-full py-4 bg-primary text-white font-bold rounded-lg hover:opacity-90 transition-colors text-center"
                      >
                        Continue
                      </Link>
                    </div>
                  )}
                </div>
              </div>

              {/* Help Card */}
              <div className="border-t-2 border-border bg-background px-12 py-6">
                <div className="max-w-2xl mx-auto">
                  <div className="flex items-start gap-3">
                    <HelpCircle size={20} className="text-primary flex-shrink-0 mt-0.5" />
                    <div>
                      <div className="font-bold text-foreground mb-2">Need Help with Aadhaar?</div>
                      <div className="text-sm text-muted-foreground space-y-1">
                        <p>UIDAI Helpline: <span className="font-bold">1947</span> (Toll-Free)</p>
                        <p>Portal Support: <span className="font-bold">1800-XXX-XXXX</span></p>
                        <p className="text-muted-foreground">Available 24x7</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Documentation Sidebar */}
          <aside className="col-span-4 space-y-6">
            <PatternInfo />
            <ConsentRequirements />
            <SecurityNotes />
            <LegalCompliance />
          </aside>

        </div>
      </main>
    </div>
  );
}

// ==================== HELPER COMPONENTS ====================

function ProgressStep({ number, label, active, completed }: { number: number; label: string; active: boolean; completed: boolean }) {
  return (
    <div className="flex flex-col items-center gap-2">
      <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm border-2 ${
        completed
          ? 'bg-green-500 border-green-500 text-white'
          : active
          ? 'bg-primary border-primary text-white'
          : 'bg-card border-border text-gray-400'
      }`}>
        {completed ? <Check size={18} /> : number}
      </div>
      <div className={`text-xs font-medium ${active ? 'text-foreground' : 'text-gray-500'}`}>{label}</div>
    </div>
  );
}

function ConsentPoint({ text }: { text: string }) {
  return (
    <div className="flex items-start gap-2">
      <Check size={16} className="text-green-600 flex-shrink-0 mt-0.5" />
      <span>{text}</span>
    </div>
  );
}

function VerifiedDetail({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between">
      <span className="font-bold text-muted-foreground">{label}:</span>
      <span className="text-foreground">{value}</span>
    </div>
  );
}

// ==================== SIDEBAR COMPONENTS ====================

function PatternInfo() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3">
        <h3 className="font-bold text-foreground">Pattern Info</h3>
      </div>
      <div className="p-4 space-y-3 text-sm">
        <InfoRow label="Pattern ID" value="UX4G-PAT-009-07" />
        <InfoRow label="Status" value="Stable" badge="green" />
        <InfoRow label="Complexity" value="High" />
        <InfoRow label="Category" value="Authentication" />
        <InfoRow label="Version" value="1.0.0" />
      </div>
    </div>
  );
}

function ConsentRequirements() {
  return (
    <div className="border-2 border-blue-200 dark:border-blue-800 rounded-lg overflow-hidden bg-blue-50">
      <div className="bg-blue-100 border-b-2 border-blue-200 dark:border-blue-800 px-4 py-3">
        <h3 className="font-bold text-foreground">Consent Required</h3>
      </div>
      <div className="p-4 space-y-2 text-sm text-muted-foreground">
        <ConsentItem text="Explicit consent before collection" />
        <ConsentItem text="Clear explanation of data use" />
        <ConsentItem text="User must actively accept terms" />
        <ConsentItem text="Right to withdraw consent" />
        <ConsentItem text="Audit trail of consent" />
      </div>
    </div>
  );
}

function SecurityNotes() {
  return (
    <div className="border-2 border-red-200 dark:border-red-800 rounded-lg overflow-hidden bg-red-50">
      <div className="bg-red-100 border-b-2 border-red-200 dark:border-red-800 px-4 py-3">
        <h3 className="font-bold text-foreground">Security</h3>
      </div>
      <div className="p-4 space-y-2 text-sm text-muted-foreground">
        <SecurityItem text="256-bit SSL/TLS encryption" />
        <SecurityItem text="Aadhaar number never stored" />
        <SecurityItem text="OTP sent via UIDAI gateway" />
        <SecurityItem text="Tokenized authentication" />
        <SecurityItem text="Logging and monitoring" />
      </div>
    </div>
  );
}

function LegalCompliance() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3">
        <h3 className="font-bold text-foreground">Legal Compliance</h3>
      </div>
      <div className="p-4 space-y-3 text-sm text-muted-foreground">
        <LegalItem
          title="Aadhaar Act, 2016"
          description="Complies with all provisions and amendments"
        />
        <LegalItem
          title="IT Act, 2000"
          description="Follows information security standards"
        />
        <LegalItem
          title="UIDAI Guidelines"
          description="Adheres to authentication protocols"
        />
      </div>
    </div>
  );
}

// Helper Components
function InfoRow({ label, value, badge }: { label: string; value: string; badge?: string }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-muted-foreground">{label}</span>
      {badge ? (
        <span className={`px-2 py-0.5 ${badge === 'green' ? 'bg-green-100 text-green-700' : 'bg-muted text-muted-foreground'} text-xs font-bold rounded-full`}>
          {value}
        </span>
      ) : (
        <span className="font-bold text-foreground">{value}</span>
      )}
    </div>
  );
}

function ConsentItem({ text }: { text: string }) {
  return (
    <div className="flex items-start gap-2">
      <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
      <span>{text}</span>
    </div>
  );
}

function SecurityItem({ text }: { text: string }) {
  return (
    <div className="flex items-start gap-2">
      <Shield size={14} className="text-red-600 flex-shrink-0 mt-0.5" />
      <span>{text}</span>
    </div>
  );
}

function LegalItem({ title, description }: { title: string; description: string }) {
  return (
    <div>
      <div className="font-bold text-foreground mb-1">{title}</div>
      <div className="text-xs text-muted-foreground">{description}</div>
    </div>
  );
}
