// src/app/angular-patterns-package/src/certificate-service/pages/identity-forgot-password/identity-forgot-password.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ServiceHeaderComponent } from '../../../services/components/service-header/service-header.component';
import { ServiceFooterComponent } from '../../../services/components/service-footer/service-footer.component';

@Component({
  selector: 'identity-forgot-password-page',
  standalone: true,
  imports: [CommonModule, FormsModule, ServiceHeaderComponent, ServiceFooterComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="fp">
      <div class="fp-tricolor" aria-hidden="true"></div>
      <header class="fp-gov">
        <span class="fp-gov__icon" aria-hidden="true">🛡️</span>
        <div><div class="fp-gov__title">Government of India</div><div class="fp-gov__sub">Unified Identity Service — Password Recovery</div></div>
      </header>

      <main class="fp-main">
        <div class="fp-content">
          <div class="fp-form-col">
            <!-- Progress Indicator -->
            <div class="fp-progress" role="navigation" aria-label="Password recovery steps">
              <div *ngFor="let s of stepLabels; let i = index" class="fp-step" [class.fp-step--active]="step === i + 1" [class.fp-step--done]="step > i + 1">
                <div class="fp-step__num">{{ step > i + 1 ? '✓' : i + 1 }}</div>
                <div class="fp-step__label">{{ s }}</div>
              </div>
            </div>

            <!-- Step 1: Identify -->
            <div class="fp-card" *ngIf="step === 1">
              <h1 class="fp-card__title">Forgot Your Password?</h1>
              <p class="fp-card__desc">Choose how you'd like to receive your verification code.</p>

              <div class="fp-methods" role="radiogroup" aria-label="Recovery method">
                <label class="fp-method" [class.fp-method--active]="method === 'mobile'">
                  <input type="radio" name="method" value="mobile" [(ngModel)]="method" hidden />
                  📱 Mobile Number
                </label>
                <label class="fp-method" [class.fp-method--active]="method === 'email'">
                  <input type="radio" name="method" value="email" [(ngModel)]="method" hidden />
                  📧 Email Address
                </label>
              </div>

              <div class="fp-field">
                <label class="fp-label">{{ method === 'mobile' ? 'Mobile Number' : 'Email Address' }}</label>
                <input class="fp-input" [type]="method === 'mobile' ? 'tel' : 'email'" [(ngModel)]="identifier" name="identifier" [placeholder]="method === 'mobile' ? '+91 XXXXX XXXXX' : 'your.email@example.com'" />
              </div>

              <button type="button" class="fp-btn fp-btn--primary" [disabled]="!identifier.trim()" (click)="step = 2">Send Verification Code</button>
            </div>

            <!-- Step 2: Verify -->
            <div class="fp-card" *ngIf="step === 2">
              <h1 class="fp-card__title">Enter Verification Code</h1>
              <p class="fp-card__desc">We've sent a 6-digit code to your {{ method }}.</p>

              <div class="fp-otp-group" role="group" aria-label="Enter 6-digit code">
                <input *ngFor="let d of otpDigits; let i = index" class="fp-otp-input" type="text" inputmode="numeric" maxlength="1" [attr.aria-label]="'Digit ' + (i + 1)" [(ngModel)]="otpDigits[i]" [attr.name]="'otp' + i" />
              </div>

              <button type="button" class="fp-btn fp-btn--primary" [disabled]="!otpComplete" (click)="step = 3">Verify Code</button>
            </div>

            <!-- Step 3: Reset -->
            <div class="fp-card" *ngIf="step === 3">
              <h1 class="fp-card__title">Create New Password</h1>
              <p class="fp-card__desc">Choose a strong password for your account.</p>

              <div class="fp-field">
                <label class="fp-label">New Password <span class="fp-req">*</span></label>
                <input class="fp-input" type="password" [(ngModel)]="newPassword" name="newPassword" placeholder="Enter new password" />
                <div class="fp-reqs" role="list" aria-label="Password requirements">
                  <div *ngFor="let r of pwdReqs" class="fp-req-item" [class.fp-req-item--met]="r.met" role="listitem">
                    {{ r.met ? '✅' : '⬜' }} {{ r.label }}
                  </div>
                </div>
              </div>

              <div class="fp-field">
                <label class="fp-label">Confirm Password <span class="fp-req">*</span></label>
                <input class="fp-input" type="password" [(ngModel)]="confirmPassword" name="confirmPassword" placeholder="Re-enter new password" />
                <div *ngIf="confirmPassword" class="fp-match" [class.fp-match--ok]="passwordsMatch" [class.fp-match--no]="!passwordsMatch">
                  {{ passwordsMatch ? '✅ Passwords match' : '❌ Passwords do not match' }}
                </div>
              </div>

              <button type="button" class="fp-btn fp-btn--primary" [disabled]="!canReset" (click)="step = 4">Reset Password</button>
            </div>

            <!-- Step 4: Success -->
            <div class="fp-card fp-card--success" *ngIf="step === 4">
              <div class="fp-success-icon" aria-hidden="true">✅</div>
              <h1 class="fp-card__title">Password Reset Successful</h1>
              <p class="fp-card__desc">Your password has been updated. You can now sign in with your new password.</p>

              <div class="fp-tips">
                <h3>Security Tips</h3>
                <ul>
                  <li>Never share your password with anyone</li>
                  <li>Use a unique password for each service</li>
                  <li>Enable two-factor authentication when available</li>
                  <li>Change your password regularly</li>
                </ul>
              </div>

              <a class="fp-btn fp-btn--primary" href="/reference-service/certificate/identity/sign-in">Go to Sign In</a>
            </div>
          </div>

          <aside class="fp-sidebar">
            <div class="fp-panel"><h2 class="fp-panel__title">Pattern Info</h2><p class="fp-panel__text">Multi-step password recovery with progressive disclosure. Each step validates before advancing.</p></div>
            <div class="fp-panel"><h2 class="fp-panel__title">User Journey</h2>
              <ol class="fp-list-ol"><li>Choose recovery method</li><li>Receive and enter OTP</li><li>Create new password</li><li>Confirmation and redirect</li></ol>
            </div>
            <div class="fp-panel"><h2 class="fp-panel__title">Security Considerations</h2>
              <ul class="fp-list"><li>OTP expires after 5 minutes</li><li>Max 3 verification attempts</li><li>Rate limiting on resend</li><li>Password history check</li></ul>
            </div>
            <div class="fp-panel"><h2 class="fp-panel__title">Accessibility</h2>
              <ul class="fp-list"><li>Step indicator with ARIA navigation</li><li>Focus management between steps</li><li>Error announcements via aria-live</li></ul>
            </div>
            <div class="fp-panel"><h2 class="fp-panel__title">Implementation</h2>
              <ul class="fp-list"><li>Client-side step management</li><li>Server-side OTP validation</li><li>Password hashing with bcrypt</li><li>Session invalidation on reset</li></ul>
            </div>
          </aside>
        </div>
      </main>

      <ux4g-service-footer leftText="Unified Identity Service • Government of India" rightText="Password Recovery"></ux4g-service-footer>
    </div>
  `,
  styles: [`
    .fp { min-height: 100vh; background: var(--ux4g-svc-bg-muted, #f8fafc); font-family: system-ui, sans-serif; color: var(--ux4g-svc-fg, #0f172a); }
    .fp-tricolor { height: 4px; background: linear-gradient(to right, #ff9933 33%, #fff 33%, #fff 66%, #138808 66%); }
    .fp-gov { display: flex; align-items: center; gap: 0.75rem; padding: 1rem 2rem; background: var(--ux4g-svc-bg, #fff); border-bottom: 2px solid var(--ux4g-svc-border, #e2e8f0); }
    .fp-gov__icon { font-size: 1.75rem; }
    .fp-gov__title { font-weight: 700; font-size: 1rem; }
    .fp-gov__sub { font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); }
    .fp-main { max-width: 1200px; margin: 0 auto; padding: 2rem 1.5rem; }
    .fp-content { display: grid; grid-template-columns: 2fr 1fr; gap: 2rem; }
    .fp-form-col { max-width: 560px; }
    .fp-progress { display: flex; gap: 0.5rem; margin-bottom: 1.5rem; }
    .fp-step { display: flex; align-items: center; gap: 0.375rem; flex: 1; padding: 0.625rem; background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.375rem; font-size: 0.75rem; color: var(--ux4g-svc-fg-muted, #64748b); }
    .fp-step--active { border-color: var(--ux4g-svc-primary, #4f46e5); color: var(--ux4g-svc-primary, #4f46e5); font-weight: 700; }
    .fp-step--done { border-color: #16a34a; color: #16a34a; }
    .fp-step__num { width: 1.5rem; height: 1.5rem; border-radius: 50%; background: var(--ux4g-svc-border, #e2e8f0); display: flex; align-items: center; justify-content: center; font-size: 0.6875rem; font-weight: 700; flex-shrink: 0; }
    .fp-step--active .fp-step__num { background: var(--ux4g-svc-primary, #4f46e5); color: #fff; }
    .fp-step--done .fp-step__num { background: #16a34a; color: #fff; }
    .fp-card { background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; padding: 2rem; }
    .fp-card--success { text-align: center; }
    .fp-card__title { font-size: 1.5rem; font-weight: 800; margin: 0 0 0.25rem; }
    .fp-card__desc { font-size: 0.875rem; color: var(--ux4g-svc-fg-muted, #64748b); margin: 0 0 1.5rem; }
    .fp-methods { display: grid; grid-template-columns: 1fr 1fr; gap: 0.75rem; margin-bottom: 1.5rem; }
    .fp-method { display: block; padding: 0.875rem; border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.375rem; text-align: center; font-size: 0.875rem; font-weight: 700; cursor: pointer; }
    .fp-method--active { border-color: var(--ux4g-svc-primary, #4f46e5); background: #eff6ff; color: var(--ux4g-svc-primary, #4f46e5); }
    .fp-field { margin-bottom: 1.25rem; }
    .fp-label { display: block; font-size: 0.875rem; font-weight: 700; margin-bottom: 0.375rem; }
    .fp-req { color: #dc2626; }
    .fp-input { width: 100%; padding: 0.625rem 0.75rem; border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.375rem; font-size: 0.875rem; box-sizing: border-box; }
    .fp-input:focus { border-color: var(--ux4g-svc-primary, #4f46e5); outline: none; }
    .fp-otp-group { display: flex; justify-content: center; gap: 0.75rem; margin-bottom: 1.5rem; }
    .fp-otp-input { width: 3rem; height: 3.5rem; text-align: center; font-size: 1.5rem; font-weight: 700; border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; }
    .fp-otp-input:focus { border-color: var(--ux4g-svc-primary, #4f46e5); outline: none; }
    .fp-reqs { display: grid; grid-template-columns: 1fr 1fr; gap: 0.25rem; margin-top: 0.5rem; }
    .fp-req-item { font-size: 0.75rem; color: var(--ux4g-svc-fg-muted, #64748b); }
    .fp-req-item--met { color: #16a34a; }
    .fp-match { font-size: 0.75rem; margin-top: 0.25rem; }
    .fp-match--ok { color: #16a34a; }
    .fp-match--no { color: #dc2626; }
    .fp-btn { display: block; width: 100%; padding: 0.75rem; font-size: 0.875rem; font-weight: 700; border-radius: 0.375rem; border: none; cursor: pointer; text-align: center; text-decoration: none; }
    .fp-btn--primary { background: var(--ux4g-svc-primary, #4f46e5); color: #fff; }
    .fp-btn:disabled { background: #9ca3af; cursor: not-allowed; }
    .fp-success-icon { font-size: 3rem; margin-bottom: 0.5rem; }
    .fp-tips { text-align: left; background: var(--ux4g-svc-bg-muted, #f8fafc); border: 1px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.375rem; padding: 1rem; margin-bottom: 1.5rem; }
    .fp-tips h3 { font-size: 0.875rem; font-weight: 700; margin: 0 0 0.5rem; }
    .fp-tips ul { margin: 0; padding-left: 1.25rem; font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); line-height: 1.8; }
    .fp-sidebar { display: flex; flex-direction: column; gap: 1rem; }
    .fp-panel { background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; padding: 1.25rem; }
    .fp-panel__title { font-size: 0.875rem; font-weight: 700; margin: 0 0 0.75rem; }
    .fp-panel__text { font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); margin: 0; }
    .fp-list, .fp-list-ol { margin: 0; padding-left: 1.25rem; font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); line-height: 1.8; }
    @media (max-width: 768px) {
      .fp-content { grid-template-columns: 1fr; }
      .fp-form-col { max-width: 100%; }
      .fp-progress { flex-wrap: wrap; }
      .fp-methods { grid-template-columns: 1fr; }
      .fp-reqs { grid-template-columns: 1fr; }
    }
  `],
})
export class IdentityForgotPasswordComponent {
  step = 1;
  stepLabels = ['Identify', 'Verify', 'Reset', 'Success'];
  method: 'mobile' | 'email' = 'mobile';
  identifier = '';
  otpDigits: string[] = ['', '', '', '', '', ''];
  newPassword = '';
  confirmPassword = '';

  get otpComplete(): boolean { return this.otpDigits.every(d => d.length === 1); }
  get passwordsMatch(): boolean { return this.newPassword === this.confirmPassword && this.newPassword.length > 0; }

  get pwdReqs() {
    const p = this.newPassword;
    return [
      { label: 'At least 8 characters', met: p.length >= 8 },
      { label: 'One uppercase letter', met: /[A-Z]/.test(p) },
      { label: 'One lowercase letter', met: /[a-z]/.test(p) },
      { label: 'One number', met: /\d/.test(p) },
      { label: 'One special character', met: /[^A-Za-z0-9]/.test(p) },
    ];
  }

  get canReset(): boolean { return this.pwdReqs.every(r => r.met) && this.passwordsMatch; }
}

// src/app/pages/IdentityForgotPassword.tsx
import { Link } from "react-router";
import { ArrowLeft, Shield, Key, Eye, EyeOff, Check, X, Phone, Mail, Info, HelpCircle, CheckCircle, AlertCircle } from "lucide-react";
import { useState } from "react";

export default function IdentityForgotPassword() {
  const [step, setStep] = useState<"identify" | "verify" | "reset" | "success">("identify");
  const [recoveryMethod, setRecoveryMethod] = useState<"mobile" | "email">("mobile");
  const [identifier, setIdentifier] = useState("");
  const [otp, setOtp] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showNewPassword, setShowNewPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);

  const passwordRequirements = [
    { label: "At least 8 characters", met: newPassword.length >= 8 },
    { label: "One uppercase letter", met: /[A-Z]/.test(newPassword) },
    { label: "One lowercase letter", met: /[a-z]/.test(newPassword) },
    { label: "One number", met: /[0-9]/.test(newPassword) },
    { label: "One special character", met: /[!@#$%^&*]/.test(newPassword) }
  ];

  const allRequirementsMet = passwordRequirements.every(req => req.met);
  const passwordsMatch = newPassword === confirmPassword && confirmPassword !== "";

  const handleSendOTP = () => {
    // Validate identifier and send OTP
    setStep("verify");
  };

  const handleVerifyOTP = () => {
    // Verify OTP code
    setStep("reset");
  };

  const handleResetPassword = () => {
    // Reset password
    setStep("success");
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation Bar */}
      <nav className="bg-card border-b-2 border-border">
        <div className="max-w-[1400px] mx-auto px-8 py-4 flex items-center justify-between">
          <Link to="/patterns/identity" className="flex items-center gap-2 text-muted-foreground hover:text-primary">
            <ArrowLeft size={20} />
            <span className="font-medium">Back to Identity Patterns</span>
          </Link>
          <div className="text-sm text-muted-foreground">
            <span className="font-bold">Flow:</span> Forgot Password / Reset
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-[1400px] mx-auto px-8 py-12">
        <div className="grid grid-cols-12 gap-8">
          
          {/* Prototype View - 8 columns */}
          <div className="col-span-8">
            <div className="bg-card border-2 border-border rounded-lg overflow-hidden shadow-lg">
              {/* Tricolor Header */}
              <div className="bg-gradient-to-r from-orange-500 via-white to-green-500 h-2"></div>
              
              {/* Government Header */}
              <div className="bg-card border-b-2 border-border px-8 py-6">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 bg-primary rounded flex items-center justify-center">
                      <Shield size={24} className="text-white" />
                    </div>
                    <div>
                      <div className="font-bold text-lg text-foreground">Digital India Portal</div>
                      <div className="text-sm text-muted-foreground">Government of India</div>
                    </div>
                  </div>
                  <div className="text-sm text-muted-foreground">
                    Remember password? <Link to="/patterns/identity/sign-in" className="text-primary font-bold hover:underline">Sign In</Link>
                  </div>
                </div>
              </div>

              {/* Progress Indicator */}
              <div className="bg-muted border-b-2 border-border px-12 py-4">
                <div className="flex items-center justify-between max-w-2xl mx-auto">
                  <ProgressStep number={1} label="Identify" active={step === "identify"} completed={step !== "identify"} />
                  <div className={`flex-1 h-0.5 mx-2 ${step !== "identify" ? 'bg-green-500' : 'bg-gray-300'}`}></div>
                  <ProgressStep number={2} label="Verify OTP" active={step === "verify"} completed={step === "reset" || step === "success"} />
                  <div className={`flex-1 h-0.5 mx-2 ${step === "reset" || step === "success" ? 'bg-green-500' : 'bg-gray-300'}`}></div>
                  <ProgressStep number={3} label="Reset Password" active={step === "reset"} completed={step === "success"} />
                  <div className={`flex-1 h-0.5 mx-2 ${step === "success" ? 'bg-green-500' : 'bg-gray-300'}`}></div>
                  <ProgressStep number={4} label="Complete" active={step === "success"} completed={false} />
                </div>
              </div>

              {/* Form Content */}
              <div className="px-12 py-10">
                <div className="max-w-2xl mx-auto">
                  {/* Step 1: Identify Account */}
                  {step === "identify" && (
                    <div>
                      <div className="w-20 h-20 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-6">
                        <Key size={40} className="text-red-600" />
                      </div>
                      <h1 className="text-3xl font-bold text-foreground mb-3 text-center">Reset Your Password</h1>
                      <p className="text-muted-foreground mb-8 text-center">
                        Enter your registered mobile number or email to receive a verification code
                      </p>

                      {/* Recovery Method Selection */}
                      <div className="mb-6">
                        <label className="block text-sm font-bold text-foreground mb-3">
                          Choose Recovery Method
                        </label>
                        <div className="grid grid-cols-2 gap-4">
                          <button
                            onClick={() => setRecoveryMethod("mobile")}
                            className={`flex items-center gap-3 p-4 border-2 rounded-lg font-medium transition-colors ${
                              recoveryMethod === "mobile"
                                ? 'border-primary bg-blue-50 text-primary'
                                : 'border-border bg-card text-muted-foreground hover:border-gray-400'
                            }`}
                          >
                            <Phone size={20} />
                            <span>Mobile Number</span>
                            {recoveryMethod === "mobile" && <Check size={20} className="ml-auto" />}
                          </button>
                          <button
                            onClick={() => setRecoveryMethod("email")}
                            className={`flex items-center gap-3 p-4 border-2 rounded-lg font-medium transition-colors ${
                              recoveryMethod === "email"
                                ? 'border-primary bg-blue-50 text-primary'
                                : 'border-border bg-card text-muted-foreground hover:border-gray-400'
                            }`}
                          >
                            <Mail size={20} />
                            <span>Email Address</span>
                            {recoveryMethod === "email" && <Check size={20} className="ml-auto" />}
                          </button>
                        </div>
                      </div>

                      {/* Input Field */}
                      <div className="mb-8">
                        <label htmlFor="identifier" className="block text-sm font-bold text-foreground mb-2">
                          {recoveryMethod === "mobile" ? "Mobile Number" : "Email Address"} <span className="text-red-600">*</span>
                        </label>
                        <div className="relative">
                          {recoveryMethod === "mobile" ? (
                            <Phone size={20} className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
                          ) : (
                            <Mail size={20} className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
                          )}
                          <input
                            type={recoveryMethod === "mobile" ? "tel" : "email"}
                            id="identifier"
                            value={identifier}
                            onChange={(e) => setIdentifier(e.target.value)}
                            className="w-full pl-12 pr-4 py-4 border-2 border-border rounded-lg text-foreground focus:border-primary focus:outline-none text-lg"
                            placeholder={recoveryMethod === "mobile" ? "+91 XXXXX XXXXX" : "your.email@example.com"}
                          />
                        </div>
                      </div>

                      <button
                        onClick={handleSendOTP}
                        disabled={!identifier}
                        className="w-full py-4 bg-primary text-white font-bold rounded-lg hover:opacity-90 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
                      >
                        Send Verification Code
                      </button>
                    </div>
                  )}

                  {/* Step 2: Verify OTP */}
                  {step === "verify" && (
                    <div>
                      <div className="w-20 h-20 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-6">
                        {recoveryMethod === "mobile" ? <Phone size={40} className="text-primary" /> : <Mail size={40} className="text-primary" />}
                      </div>
                      <h1 className="text-3xl font-bold text-foreground mb-3 text-center">Enter Verification Code</h1>
                      <p className="text-muted-foreground mb-2 text-center">
                        We've sent a 6-digit code to
                      </p>
                      <p className="text-lg font-bold text-foreground mb-8 text-center">
                        {identifier}
                      </p>

                      <div className="mb-8">
                        <label htmlFor="otp" className="block text-sm font-bold text-foreground mb-2">
                          Verification Code <span className="text-red-600">*</span>
                        </label>
                        <input
                          type="text"
                          id="otp"
                          value={otp}
                          onChange={(e) => setOtp(e.target.value.replace(/\D/g, '').slice(0, 6))}
                          className="w-full px-4 py-4 border-2 border-border rounded-lg text-center text-2xl font-bold tracking-widest focus:border-primary focus:outline-none"
                          placeholder="______"
                          maxLength={6}
                        />
                        <div className="text-sm text-muted-foreground mt-2">
                          Didn't receive the code? <button className="text-primary font-bold hover:underline">Resend Code</button>
                        </div>
                      </div>

                      <button
                        onClick={handleVerifyOTP}
                        disabled={otp.length !== 6}
                        className="w-full py-4 bg-primary text-white font-bold rounded-lg hover:opacity-90 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
                      >
                        Verify Code
                      </button>
                    </div>
                  )}

                  {/* Step 3: Reset Password */}
                  {step === "reset" && (
                    <div>
                      <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
                        <Key size={40} className="text-green-600" />
                      </div>
                      <h1 className="text-3xl font-bold text-foreground mb-3 text-center">Create New Password</h1>
                      <p className="text-muted-foreground mb-8 text-center">
                        Choose a strong password that you haven't used before
                      </p>

                      {/* New Password */}
                      <div className="mb-6">
                        <label htmlFor="newPassword" className="block text-sm font-bold text-foreground mb-2">
                          New Password <span className="text-red-600">*</span>
                        </label>
                        <div className="relative">
                          <Key size={20} className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
                          <input
                            type={showNewPassword ? "text" : "password"}
                            id="newPassword"
                            value={newPassword}
                            onChange={(e) => setNewPassword(e.target.value)}
                            className="w-full pl-12 pr-12 py-4 border-2 border-border rounded-lg text-foreground focus:border-primary focus:outline-none text-lg"
                            placeholder="Enter new password"
                          />
                          <button
                            type="button"
                            onClick={() => setShowNewPassword(!showNewPassword)}
                            className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-muted-foreground"
                          >
                            {showNewPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                          </button>
                        </div>
                      </div>

                      {/* Password Requirements */}
                      <div className="mb-6 p-4 bg-background border-2 border-border rounded-lg">
                        <div className="text-sm font-bold text-foreground mb-3">Password must contain:</div>
                        <div className="grid grid-cols-2 gap-2">
                          {passwordRequirements.map((req, idx) => (
                            <div key={idx} className="flex items-center gap-2 text-sm">
                              {req.met ? (
                                <Check size={14} className="text-green-600" />
                              ) : (
                                <X size={14} className="text-gray-400" />
                              )}
                              <span className={req.met ? "text-green-700" : "text-muted-foreground"}>{req.label}</span>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Confirm Password */}
                      <div className="mb-8">
                        <label htmlFor="confirmPassword" className="block text-sm font-bold text-foreground mb-2">
                          Confirm New Password <span className="text-red-600">*</span>
                        </label>
                        <div className="relative">
                          <Key size={20} className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
                          <input
                            type={showConfirmPassword ? "text" : "password"}
                            id="confirmPassword"
                            value={confirmPassword}
                            onChange={(e) => setConfirmPassword(e.target.value)}
                            className="w-full pl-12 pr-12 py-4 border-2 border-border rounded-lg text-foreground focus:border-primary focus:outline-none text-lg"
                            placeholder="Re-enter new password"
                          />
                          <button
                            type="button"
                            onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                            className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 hover:text-muted-foreground"
                          >
                            {showConfirmPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                          </button>
                        </div>
                        {confirmPassword && !passwordsMatch && (
                          <div className="flex items-center gap-2 mt-2 text-sm text-red-600">
                            <X size={14} />
                            <span>Passwords do not match</span>
                          </div>
                        )}
                        {passwordsMatch && (
                          <div className="flex items-center gap-2 mt-2 text-sm text-green-600">
                            <Check size={14} />
                            <span>Passwords match</span>
                          </div>
                        )}
                      </div>

                      <button
                        onClick={handleResetPassword}
                        disabled={!allRequirementsMet || !passwordsMatch}
                        className="w-full py-4 bg-primary text-white font-bold rounded-lg hover:opacity-90 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
                      >
                        Reset Password
                      </button>
                    </div>
                  )}

                  {/* Step 4: Success */}
                  {step === "success" && (
                    <div className="text-center">
                      <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
                        <CheckCircle size={40} className="text-green-600" />
                      </div>
                      <h1 className="text-3xl font-bold text-foreground mb-3">Password Reset Successful!</h1>
                      <p className="text-muted-foreground mb-8">
                        Your password has been changed successfully. You can now sign in with your new password.
                      </p>

                      <div className="p-6 bg-blue-50 border-2 border-blue-200 rounded-lg mb-8">
                        <div className="flex items-start gap-3 text-left">
                          <Info size={20} className="text-blue-600 flex-shrink-0 mt-0.5" />
                          <div className="text-sm text-muted-foreground">
                            <div className="font-bold text-foreground mb-2">Security Tip</div>
                            <ul className="space-y-1 text-muted-foreground">
                              <li>• Don't share your password with anyone</li>
                              <li>• Use a unique password for this account</li>
                              <li>• Change your password regularly</li>
                            </ul>
                          </div>
                        </div>
                      </div>

                      <Link
                        to="/patterns/identity/sign-in"
                        className="block w-full py-4 bg-primary text-white font-bold rounded-lg hover:opacity-90 transition-colors text-center"
                      >
                        Go to Sign In
                      </Link>
                    </div>
                  )}
                </div>
              </div>

              {/* Help Card */}
              <div className="border-t-2 border-border bg-background px-12 py-6">
                <div className="max-w-2xl mx-auto">
                  <div className="flex items-start gap-3">
                    <HelpCircle size={20} className="text-primary flex-shrink-0 mt-0.5" />
                    <div>
                      <div className="font-bold text-foreground mb-2">Need Help?</div>
                      <div className="text-sm text-muted-foreground space-y-1">
                        <p>Call: <span className="font-bold">1800-XXX-XXXX</span> (Toll-Free)</p>
                        <p>Email: <span className="font-bold">support@digitalindia.gov.in</span></p>
                        <p className="text-muted-foreground">Monday to Friday, 9:00 AM - 6:00 PM IST</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Documentation Sidebar - 4 columns */}
          <aside className="col-span-4 space-y-6">
            <PatternInfo />
            <UserJourney />
            <SecurityConsiderations />
            <AccessibilityNotes />
            <ImplementationNotes />
          </aside>

        </div>
      </main>
    </div>
  );
}

// ==================== HELPER COMPONENTS ====================

function ProgressStep({ number, label, active, completed }: { number: number; label: string; active: boolean; completed: boolean }) {
  return (
    <div className="flex flex-col items-center gap-2">
      <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm border-2 ${
        completed
          ? 'bg-green-500 border-green-500 text-white'
          : active
          ? 'bg-primary border-primary text-white'
          : 'bg-card border-border text-gray-400'
      }`}>
        {completed ? <Check size={18} /> : number}
      </div>
      <div className={`text-xs font-medium ${active ? 'text-foreground' : 'text-gray-500'}`}>{label}</div>
    </div>
  );
}

// ==================== SIDEBAR COMPONENTS ====================

function PatternInfo() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3">
        <h3 className="font-bold text-foreground">Pattern Info</h3>
      </div>
      <div className="p-4 space-y-3 text-sm">
        <InfoRow label="Pattern ID" value="UX4G-PAT-009-05" />
        <InfoRow label="Status" value="Stable" badge="green" />
        <InfoRow label="Complexity" value="Medium" />
        <InfoRow label="Category" value="Recovery" />
        <InfoRow label="Version" value="1.0.0" />
      </div>
    </div>
  );
}

function UserJourney() {
  return (
    <div className="border-2 border-blue-200 rounded-lg overflow-hidden bg-blue-50">
      <div className="bg-blue-100 border-b-2 border-blue-200 px-4 py-3">
        <h3 className="font-bold text-foreground">User Journey</h3>
      </div>
      <div className="p-4 space-y-3 text-sm text-muted-foreground">
        <JourneyStep number="1" text="Identify account (mobile/email)" />
        <JourneyStep number="2" text="Receive OTP verification code" />
        <JourneyStep number="3" text="Verify OTP code" />
        <JourneyStep number="4" text="Create new password" />
        <JourneyStep number="5" text="Confirm password reset" />
      </div>
    </div>
  );
}

function SecurityConsiderations() {
  return (
    <div className="border-2 border-red-200 rounded-lg overflow-hidden bg-red-50">
      <div className="bg-red-100 border-b-2 border-red-200 px-4 py-3">
        <h3 className="font-bold text-foreground">Security</h3>
      </div>
      <div className="p-4 space-y-2 text-sm text-muted-foreground">
        <SecurityItem text="Rate limit reset attempts (3 per hour)" />
        <SecurityItem text="OTP valid for 10 minutes only" />
        <SecurityItem text="Log all password reset attempts" />
        <SecurityItem text="Send notification email after reset" />
        <SecurityItem text="Require re-login after reset" />
      </div>
    </div>
  );
}

function AccessibilityNotes() {
  return (
    <div className="border-2 border-green-200 rounded-lg overflow-hidden bg-green-50">
      <div className="bg-green-100 border-b-2 border-green-200 px-4 py-3">
        <h3 className="font-bold text-foreground">Accessibility</h3>
      </div>
      <div className="p-4 space-y-2 text-sm text-muted-foreground">
        <AccessibilityItem text="Progress indicator visible and announced" />
        <AccessibilityItem text="All form fields properly labeled" />
        <AccessibilityItem text="Password requirements announced" />
        <AccessibilityItem text="Error messages linked to fields" />
        <AccessibilityItem text="Keyboard navigation throughout" />
      </div>
    </div>
  );
}

function ImplementationNotes() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3">
        <h3 className="font-bold text-foreground">Implementation</h3>
      </div>
      <div className="p-4 space-y-3 text-sm text-muted-foreground">
        <div>
          <div className="font-bold text-foreground mb-1">Step management</div>
          <div>Use state to track current step (identify → verify → reset → success)</div>
        </div>
        <div>
          <div className="font-bold text-foreground mb-1">OTP delivery</div>
          <div>Send via SMS Gateway or Email Service with retry logic</div>
        </div>
        <div>
          <div className="font-bold text-foreground mb-1">Password validation</div>
          <div>Real-time validation with visual feedback for each requirement</div>
        </div>
      </div>
    </div>
  );
}

// Helper Components
function InfoRow({ label, value, badge }: { label: string; value: string; badge?: string }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-muted-foreground">{label}</span>
      {badge ? (
        <span className={`px-2 py-0.5 ${badge === 'green' ? 'bg-green-100 text-green-700' : 'bg-muted text-muted-foreground'} text-xs font-bold rounded-full`}>
          {value}
        </span>
      ) : (
        <span className="font-bold text-foreground">{value}</span>
      )}
    </div>
  );
}

function JourneyStep({ number, text }: { number: string; text: string }) {
  return (
    <div className="flex items-start gap-3">
      <div className="w-6 h-6 rounded-full bg-blue-200 text-blue-700 flex items-center justify-center flex-shrink-0 font-bold text-xs">
        {number}
      </div>
      <span>{text}</span>
    </div>
  );
}

function SecurityItem({ text }: { text: string }) {
  return (
    <div className="flex items-start gap-2">
      <AlertCircle size={14} className="text-red-600 flex-shrink-0 mt-0.5" />
      <span>{text}</span>
    </div>
  );
}

function AccessibilityItem({ text }: { text: string }) {
  return (
    <div className="flex items-start gap-2">
      <CheckCircle size={14} className="text-green-600 flex-shrink-0 mt-0.5" />
      <span>{text}</span>
    </div>
  );
}
