// src/app/react-core-package/src/components/Flex/Flex.tsx
import { forwardRef } from 'react';
import { cn } from '../../utils/cn';
import { FlexProps } from './Flex.types';

const dirMap = { row: 'flex-row', 'row-reverse': 'flex-row-reverse', column: 'flex-col', 'column-reverse': 'flex-col-reverse' };
const alignMap = { start: 'items-start', center: 'items-center', end: 'items-end', stretch: 'items-stretch', baseline: 'items-baseline' };
const justifyMap = { start: 'justify-start', center: 'justify-center', end: 'justify-end', between: 'justify-between', around: 'justify-around', evenly: 'justify-evenly' };
const wrapMap = { nowrap: 'flex-nowrap', wrap: 'flex-wrap', 'wrap-reverse': 'flex-wrap-reverse' };

export const Flex = forwardRef<HTMLDivElement, FlexProps>(
  ({ children, direction = 'row', align = 'stretch', justify = 'start', wrap = 'nowrap', gap, inline = false, className, style, ...props }, ref) => {
    const g = gap != null ? (typeof gap === 'number' ? `${gap}px` : gap) : undefined;
    return (
      <div
        ref={ref}
        className={cn('ux4g-flex', inline ? 'inline-flex' : 'flex', dirMap[direction], alignMap[align], justifyMap[justify], wrapMap[wrap], className)}
        style={{ gap: g, ...style }}
        {...props}
      >
        {children}
      </div>
    );
  }
);

Flex.displayName = 'Flex';

// src/app/angular-core-package/src/lib/flex/flex.component.ts
import { Component, Input, ChangeDetectionStrategy, ViewEncapsulation } from '@angular/core';

/**
 * Flexbox wrapper component for flexible layouts
 *
 * @example
 * // Government Form Layout
 * <ux4g-flex direction="column" gap="1.5rem">
 *   <ux4g-field>
 *     <ux4g-label>Aadhaar Number</ux4g-label>
 *     <ux4g-aadhaar-input></ux4g-aadhaar-input>
 *   </ux4g-field>
 *   <ux4g-field>
 *     <ux4g-label>PAN Number</ux4g-label>
 *     <ux4g-pan-input></ux4g-pan-input>
 *   </ux4g-field>
 * </ux4g-flex>
 *
 * @example
 * // Form Actions Row
 * <ux4g-flex justify="between" align="center" gap="1rem">
 *   <ux4g-button variant="secondary">Cancel</ux4g-button>
 *   <ux4g-flex gap="0.5rem">
 *     <ux4g-button variant="outline">Save Draft</ux4g-button>
 *     <ux4g-button variant="primary">Submit Application</ux4g-button>
 *   </ux4g-flex>
 * </ux4g-flex>
 */
@Component({
  selector: 'ux4g-flex',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <div [class]="flexClasses" [style.gap]="gap">
      <ng-content></ng-content>
    </div>
  `,
  styleUrls: ['./flex.component.css']
})
export class FlexComponent {
  @Input() direction: 'row' | 'column' | 'row-reverse' | 'column-reverse' = 'row';
  @Input() wrap: 'nowrap' | 'wrap' | 'wrap-reverse' = 'nowrap';
  @Input() justify: 'start' | 'end' | 'center' | 'between' | 'around' | 'evenly' = 'start';
  @Input() align: 'start' | 'end' | 'center' | 'baseline' | 'stretch' = 'stretch';
  @Input() gap: string = '0';
  @Input() inline: boolean = false;
  @Input() className?: string;

  get flexClasses(): string {
    const classes = [
      this.inline ? 'ux4g-flex--inline' : 'ux4g-flex',
      `ux4g-flex--direction-${this.direction}`,
      `ux4g-flex--wrap-${this.wrap}`,
      `ux4g-flex--justify-${this.justify}`,
      `ux4g-flex--align-${this.align}`
    ];

    if (this.className) {
      classes.push(this.className);
    }

    return classes.join(' ');
  }
}
