// src/app/angular-patterns-package/src/services/components/service-footer/service-footer.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'ux4g-service-footer',
  standalone: true,
  template: `
    <footer class="svc-footer">
      <div class="svc-footer__inner">
        <span>{{ leftText }}</span>
        <span>{{ rightText }}</span>
      </div>
    </footer>
  `,
  styles: [`
    .svc-footer {
      background: var(--ux4g-svc-bg, #fff);
      border-top: 2px solid var(--ux4g-svc-border, #e2e8f0);
      margin-top: 4rem;
    }
    .svc-footer__inner {
      max-width: 1400px; margin: 0 auto; padding: 1.5rem 3rem;
      display: flex; justify-content: space-between; align-items: center;
      font-size: 0.875rem; color: var(--ux4g-svc-fg-muted, #64748b);
    }
    @media (max-width: 640px) {
      .svc-footer__inner { flex-direction: column; gap: 0.5rem; text-align: center; padding: 1rem; }
    }
  `],
})
export class ServiceFooterComponent {
  @Input() leftText = '';
  @Input() rightText = '';
}

// src/app/components/certificate/ServiceFooter.tsx
import { Link } from "react-router";

interface ServiceFooterProps {
  leftText?: string;
  rightText?: string;
  links?: Array<{ to: string; text: string }>;
}

export function ServiceFooter({
  leftText = "Certificate Application Service • Government of India",
  rightText,
  links = []
}: ServiceFooterProps) {
  return (
    <footer className="mt-24" style={{
      backgroundColor: 'var(--ux4g-color-background-primary)',
      borderTop: '2px solid var(--ux4g-color-border-default)'
    }}>
      <div className="max-w-[1400px] mx-auto px-12 py-8">
        <div className="flex items-center justify-between text-sm" style={{ color: 'var(--ux4g-color-text-secondary)' }}>
          <div>{leftText}</div>
          <div className="flex items-center gap-6">
            {links.map((link, idx) => (
              <Link key={idx} to={link.to} className="font-bold hover:underline" style={{ color: 'var(--ux4g-color-interactive-default)' }}>
                {link.text}
              </Link>
            ))}
            {rightText && <div>{rightText}</div>}
          </div>
        </div>
      </div>
    </footer>
  );
}
