// src/app/pages/IdentitySignIn.tsx
import { Link } from "react-router";
import { ArrowLeft, Shield, Eye, EyeOff, User, Lock, HelpCircle, CheckCircle, Smartphone, AlertCircle } from "lucide-react";
import { useState } from "react";

export default function IdentitySignIn() {
  const [showPassword, setShowPassword] = useState(false);
  const [formData, setFormData] = useState({
    username: "",
    password: "",
    rememberMe: false
  });

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation Bar */}
      <nav className="bg-card border-b-2 border-border">
        <div className="max-w-[1400px] mx-auto px-8 py-4 flex items-center justify-between">
          <Link to="/patterns/identity" className="flex items-center gap-2 text-muted-foreground hover:text-primary">
            <ArrowLeft size={20} />
            <span className="font-medium">Back to Identity Patterns</span>
          </Link>
          <div className="text-sm text-muted-foreground">
            <span className="font-bold">Flow:</span> Sign In
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-[1400px] mx-auto px-8 py-12">
        <div className="grid grid-cols-12 gap-8">
          
          {/* Prototype View - 8 columns */}
          <div className="col-span-8">
            <div className="bg-card border-2 border-border rounded-lg overflow-hidden shadow-lg">
              {/* Tricolor Header */}
              <div className="bg-gradient-to-r from-orange-500 via-white to-green-500 h-2"></div>
              
              {/* Government Header */}
              <div className="bg-card border-b-2 border-border px-8 py-6">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 bg-primary rounded flex items-center justify-center">
                      <Shield size={24} className="text-white" />
                    </div>
                    <div>
                      <div className="font-bold text-lg text-foreground">Digital India Portal</div>
                      <div className="text-sm text-muted-foreground">Government of India</div>
                    </div>
                  </div>
                  <div className="text-sm text-muted-foreground">
                    New user? <Link to="/patterns/identity/sign-up" className="text-primary font-bold hover:underline">Create Account</Link>
                  </div>
                </div>
              </div>

              {/* Form Content */}
              <div className="px-4 sm:px-8 lg:px-12 py-10">
                <div className="max-w-xl mx-auto">
                  <h1 className="text-3xl font-bold text-foreground mb-3">Sign In to Your Account</h1>
                  <p className="text-muted-foreground mb-8">
                    Access your government services dashboard using your registered mobile number or email.
                  </p>

                  <form className="space-y-6">
                    {/* Username/Mobile */}
                    <div>
                      <label htmlFor="username" className="block text-sm font-bold text-foreground mb-2">
                        Mobile Number or Email <span className="text-red-600">*</span>
                      </label>
                      <div className="relative">
                        <User size={20} className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground" />
                        <input
                          type="text"
                          id="username"
                          value={formData.username}
                          onChange={(e) => setFormData({ ...formData, username: e.target.value })}
                          className="w-full pl-12 pr-4 py-4 border-2 border-border rounded-lg text-foreground focus:border-primary focus:outline-none text-lg"
                          placeholder="Enter mobile number or email"
                          required
                        />
                      </div>
                      <div className="text-sm text-muted-foreground mt-2">Use your registered mobile number (10 digits) or email address</div>
                    </div>

                    {/* Password */}
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <label htmlFor="password" className="block text-sm font-bold text-foreground">
                          Password <span className="text-red-600">*</span>
                        </label>
                        <Link to="/patterns/identity/forgot-password" className="text-sm text-primary font-bold hover:underline">
                          Forgot Password?
                        </Link>
                      </div>
                      <div className="relative">
                        <Lock size={20} className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground" />
                        <input
                          type={showPassword ? "text" : "password"}
                          id="password"
                          value={formData.password}
                          onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                          className="w-full pl-12 pr-14 py-4 border-2 border-border rounded-lg text-foreground focus:border-primary focus:outline-none text-lg font-mono"
                          placeholder="Enter your password"
                          required
                        />
                        <button
                          type="button"
                          onClick={() => setShowPassword(!showPassword)}
                          className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-500 hover:text-muted-foreground"
                        >
                          {showPassword ? <EyeOff size={20} /> : <Eye size={20} />}
                        </button>
                      </div>
                    </div>

                    {/* Remember Me */}
                    <div className="flex items-center gap-3">
                      <input
                        type="checkbox"
                        id="rememberMe"
                        checked={formData.rememberMe}
                        onChange={(e) => setFormData({ ...formData, rememberMe: e.target.checked })}
                        className="w-5 h-5 border-2 border-gray-400 rounded"
                      />
                      <label htmlFor="rememberMe" className="text-sm text-muted-foreground">
                        Keep me signed in on this device
                      </label>
                    </div>

                    {/* Submit Button */}
                    <div className="pt-4">
                      <button
                        type="submit"
                        className="w-full px-8 py-5 bg-primary text-white font-bold rounded-lg hover:opacity-90 text-lg transition-colors"
                      >
                        Sign In
                      </button>
                    </div>
                  </form>

                  {/* Alternative Sign In Methods */}
                  <div className="mt-8">
                    <div className="relative">
                      <div className="absolute inset-0 flex items-center">
                        <div className="w-full border-t-2 border-border"></div>
                      </div>
                      <div className="relative flex justify-center text-sm">
                        <span className="px-4 bg-card text-muted-foreground font-medium">Or sign in with</span>
                      </div>
                    </div>

                    <div className="mt-6 grid grid-cols-2 gap-4">
                      <Link
                        to="/patterns/identity/mobile-otp"
                        className="flex items-center justify-center gap-3 px-6 py-4 border-2 border-border rounded-lg hover:border-primary hover:bg-blue-50 transition-colors"
                      >
                        <Smartphone size={20} className="text-primary" />
                        <span className="font-bold text-foreground">Mobile OTP</span>
                      </Link>
                      <Link
                        to="/patterns/identity/aadhaar-auth"
                        className="flex items-center justify-center gap-3 px-6 py-4 border-2 border-border rounded-lg hover:border-primary hover:bg-blue-50 transition-colors"
                      >
                        <Shield size={20} className="text-primary" />
                        <span className="font-bold text-foreground">Aadhaar</span>
                      </Link>
                    </div>
                  </div>

                  {/* Security Notice */}
                  <div className="mt-8 bg-blue-50 dark:bg-blue-950/30 border-l-4 border-blue-600 p-4 rounded-r-lg">
                    <div className="flex items-start gap-3">
                      <Shield size={20} className="text-blue-600 flex-shrink-0 mt-0.5" />
                      <div>
                        <div className="font-bold text-sm text-foreground mb-1">Secure Connection</div>
                        <div className="text-sm text-muted-foreground">
                          Your login credentials are encrypted. Never share your password with anyone.
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Account Recovery */}
                  <div className="mt-6 text-center text-sm text-muted-foreground">
                    Can't access your account? <Link to="/patterns/identity/account-recovery" className="text-primary font-bold hover:underline">Account Recovery</Link>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Documentation Sidebar - 4 columns */}
          <div className="col-span-4 space-y-6 sticky top-24 self-start">
            <AnnotationPanel />
            <FlowNavigation />
            <HelpPanel />
          </div>

        </div>
      </main>
    </div>
  );
}

function AnnotationPanel() {
  return (
    <div className="border-2 border-blue-200 dark:border-blue-800 rounded-lg overflow-hidden bg-blue-50">
      <div className="bg-blue-100 border-b-2 border-blue-200 dark:border-blue-800 px-4 py-3">
        <h3 className="font-bold text-foreground text-sm">Design Annotations</h3>
      </div>
      <div className="p-4">
        <ul className="space-y-2 text-sm text-muted-foreground">
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>Accepts both mobile and email for flexibility</span>
          </li>
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>"Forgot Password" link prominently placed</span>
          </li>
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>Password show/hide toggle for accessibility</span>
          </li>
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>Alternative auth methods (OTP, Aadhaar) visible</span>
          </li>
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>Account recovery path clearly signposted</span>
          </li>
          <li className="flex items-start gap-2">
            <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
            <span>Security reassurance messaging present</span>
          </li>
        </ul>
      </div>
    </div>
  );
}

function FlowNavigation() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3">
        <h3 className="font-bold text-foreground text-sm">Sign In Options</h3>
      </div>
      <div className="p-4">
        <div className="space-y-3 text-sm">
          <FlowOption label="Username + Password" active={true} />
          <FlowOption label="Mobile OTP" href="/identity-mobile-otp" />
          <FlowOption label="Aadhaar Authentication" href="/identity-aadhaar" />
        </div>
      </div>
    </div>
  );
}

function FlowOption({ label, active = false, href }: { label: string; active?: boolean; href?: string }) {
  const content = (
    <div className={`flex items-center justify-between p-3 rounded ${active ? 'bg-blue-100 border-2 border-blue-300' : 'bg-background border-2 border-border hover:border-gray-400'}`}>
      <span className={`font-medium ${active ? 'text-foreground' : 'text-muted-foreground'}`}>{label}</span>
      {!active && <span className="text-xs text-primary font-bold">View →</span>}
    </div>
  );

  return href ? <Link to={href}>{content}</Link> : content;
}

function HelpPanel() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3 flex items-center gap-2">
        <HelpCircle size={16} className="text-muted-foreground" />
        <h3 className="font-bold text-foreground text-sm">Need Help?</h3>
      </div>
      <div className="p-4 space-y-4 text-sm text-muted-foreground">
        <div>
          <div className="font-bold text-foreground mb-1">Helpline</div>
          <div className="text-primary font-bold">1800-XXX-XXXX</div>
          <div className="text-xs text-muted-foreground">Mon-Sat, 9 AM - 6 PM</div>
        </div>
        <div>
          <div className="font-bold text-foreground mb-1">Common Issues</div>
          <ul className="space-y-1 text-xs">
            <li>• <Link to="/patterns/identity/forgot-password" className="text-primary hover:underline">Forgot password?</Link></li>
            <li>• <Link to="/patterns/identity/account-recovery" className="text-primary hover:underline">Account locked?</Link></li>
            <li>• <Link to="/patterns/identity/auth-error" className="text-primary hover:underline">Login errors?</Link></li>
          </ul>
        </div>
      </div>
    </div>
  );
}

// src/app/web-components-package/src/services/certificate-flow/identity-sign-in.ts
import { UX4GElement } from '../../base/UX4GElement';
const GOV = 'Government of India';
const PORTAL = 'Digital India Portal';

export class UX4GIdentitySignIn extends UX4GElement {
  private _username = ''; private _password = ''; private _showPw = false; private _remember = false;
  constructor() { super({ useShadowDOM: true }); }
  connectedCallback(): void { super.connectedCallback(); this.importUX4GStyles(); this.render(); }
  protected render(): void {
    this.root.innerHTML = `
      <style>
        :host{display:block;min-height:100vh;background:var(--ux4g-color-background,#f8fafc);font-family:system-ui,sans-serif;color:var(--ux4g-color-text-default,#0f172a)}
        .tri{height:4px;background:linear-gradient(to right,#ff9933 33%,#fff 33%,#fff 66%,#138808 66%)}
        .gov{display:flex;align-items:center;gap:.75rem;padding:1rem 2rem;background:var(--ux4g-color-surface,#fff);border-bottom:2px solid var(--ux4g-color-border,#e2e8f0)}
        .gov__icon{font-size:1.75rem}.gov__title{font-weight:700}.gov__sub{font-size:.8125rem;color:var(--ux4g-color-text-muted,#64748b)}
        .main{max-width:1200px;margin:0 auto;padding:2rem 1.5rem;display:grid;grid-template-columns:2fr 1fr;gap:2rem}
        .form-col{max-width:560px}
        .card{background:var(--ux4g-color-surface,#fff);border:2px solid var(--ux4g-color-border,#e2e8f0);border-radius:.5rem;padding:2rem}
        .card__title{font-size:1.5rem;font-weight:800;margin:0 0 .25rem}.card__desc{font-size:.875rem;color:var(--ux4g-color-text-muted,#64748b);margin:0 0 1.5rem}
        .field{margin-bottom:1.25rem}.label{display:block;font-size:.875rem;font-weight:700;margin-bottom:.375rem}
        .input{display:block;width:100%;padding:.625rem .75rem;font-size:.875rem;border:1px solid var(--ux4g-color-border,#e2e8f0);border-radius:.5rem;box-sizing:border-box;background:var(--ux4g-color-surface,#fff);color:var(--ux4g-color-text-default,#0f172a)}
        .input:focus{border-color:var(--ux4g-color-interactive-default,#000080);outline:none}
        .input-wrap{position:relative}.input-wrap .input{padding-right:2.5rem}
        .toggle{position:absolute;right:.5rem;top:50%;transform:translateY(-50%);background:none;border:none;cursor:pointer;font-size:1.125rem}
        .row{display:flex;justify-content:space-between;align-items:center;margin-bottom:1.25rem}
        .check{font-size:.8125rem;display:flex;align-items:center;gap:.375rem;cursor:pointer}
        .link{background:none;border:none;color:var(--ux4g-color-interactive-default,#000080);font-weight:600;cursor:pointer;font-size:.8125rem;text-decoration:none;padding:0}
        .link:hover{text-decoration:underline}
        .btn{width:100%;padding:.75rem;font-size:.875rem;font-weight:700;border-radius:.375rem;border:none;cursor:pointer;text-align:center}
        .btn--primary{background:var(--ux4g-color-interactive-default,#000080);color:#fff}
        .btn--outline{background:var(--ux4g-color-surface,#fff);border:2px solid var(--ux4g-color-border,#e2e8f0);color:var(--ux4g-color-text-default,#0f172a)}
        .divider{text-align:center;margin:1.5rem 0;position:relative}
        .divider::before{content:'';position:absolute;left:0;right:0;top:50%;height:1px;background:var(--ux4g-color-border,#e2e8f0)}
        .divider span{background:var(--ux4g-color-surface,#fff);padding:0 .75rem;font-size:.8125rem;color:var(--ux4g-color-text-muted,#64748b);position:relative}
        .alt{display:grid;grid-template-columns:1fr 1fr;gap:.75rem;margin-bottom:1.5rem}
        .security{background:#eff6ff;border:1px solid #93c5fd;border-radius:.375rem;padding:.75rem;font-size:.75rem;color:var(--ux4g-color-text-muted,#64748b);text-align:center;margin-bottom:1rem}
        .recovery{text-align:center;font-size:.8125rem}
        .sidebar{display:flex;flex-direction:column;gap:1rem}
        .panel{background:var(--ux4g-color-surface,#fff);border:2px solid var(--ux4g-color-border,#e2e8f0);border-radius:.5rem;padding:1.25rem}
        .panel__title{font-size:.875rem;font-weight:700;margin:0 0 .75rem}
        .panel__text{font-size:.8125rem;color:var(--ux4g-color-text-muted,#64748b);margin:0 0 .25rem}
        .panel__text--bold{font-weight:700;color:var(--ux4g-color-text-default,#0f172a)}
        .annotations{margin:0;padding-left:1.25rem;font-size:.8125rem;color:var(--ux4g-color-text-muted,#64748b);line-height:1.8}
        @media(max-width:768px){.main{grid-template-columns:1fr}.form-col{max-width:100%}.alt{grid-template-columns:1fr}}
      </style>
      <div class="tri" aria-hidden="true"></div>
      <header class="gov"><span class="gov__icon" aria-hidden="true">🛡️</span><div><div class="gov__title">${PORTAL}</div><div class="gov__sub">${GOV}</div></div></header>
      <div class="main">
        <div class="form-col"><div class="card">
          <h1 class="card__title">Sign In to Your Account</h1>
          <p class="card__desc">Access your government services dashboard.</p>
          <form id="si-form" novalidate>
            <div class="field"><label class="label">Mobile Number or Email</label><input class="input" id="si-user" type="text" placeholder="Enter mobile number or email" autocomplete="username" /></div>
            <div class="field"><label class="label">Password</label><div class="input-wrap"><input class="input" id="si-pw" type="${this._showPw?'text':'password'}" placeholder="Enter your password" autocomplete="current-password" /><button type="button" class="toggle" id="si-toggle">${this._showPw?'🙈':'👁'}</button></div></div>
            <div class="row"><label class="check"><input type="checkbox" id="si-rem" ${this._remember?'checked':''} /> Remember me</label><a class="link" href="/patterns/identity/forgot-password">Forgot Password?</a></div>
            <button type="submit" class="btn btn--primary">Sign In</button>
          </form>
          <div class="divider"><span>Or sign in with</span></div>
          <div class="alt"><a href="/patterns/identity/mobile-otp" class="btn btn--outline">📱 Mobile OTP</a><a href="/patterns/identity/aadhaar-auth" class="btn btn--outline">🛡 Aadhaar</a></div>
          <div class="security">🔒 Your connection is encrypted and secure.</div>
          <div class="recovery"><a href="/patterns/identity/account-recovery" class="link">Can't access your account? Recover it here →</a></div>
        </div></div>
        <aside class="sidebar">
          <div class="panel"><h2 class="panel__title">Design Annotations</h2><ul class="annotations"><li>Accepts both mobile and email</li><li>Forgot Password prominently placed</li><li>Password show/hide toggle</li><li>Alternative auth methods visible</li><li>Account recovery path signposted</li><li>Security reassurance messaging</li></ul></div>
          <div class="panel"><h2 class="panel__title">Sign In Options</h2><p class="panel__text">Username + Password, Mobile OTP, Aadhaar Authentication</p></div>
          <div class="panel"><h2 class="panel__title">Help</h2><p class="panel__text panel__text--bold">📞 1800-XXX-XXXX</p><p class="panel__text">Mon–Sat, 9 AM – 6 PM</p></div>
        </aside>
      </div>
      <ux4g-service-footer left-text="Unified Identity Service • ${GOV}" right-text="Sign In"></ux4g-service-footer>
    `;
    this.root.querySelector('#si-toggle')?.addEventListener('click',()=>{this._showPw=!this._showPw;this.render();});
  }
}
if(!customElements.get('ux4g-identity-sign-in'))customElements.define('ux4g-identity-sign-in',UX4GIdentitySignIn);
