// src/app/pages/IdentityEmailOTP.tsx
import { Link } from "react-router";
import { ArrowLeft, Shield, Mail, RefreshCw, Info, HelpCircle, CheckCircle, Clock } from "lucide-react";
import { useState, useEffect } from "react";

export default function IdentityEmailOTP() {
  const [otp, setOtp] = useState(["", "", "", "", "", ""]);
  const [countdown, setCountdown] = useState(120); // 2 minutes
  const [canResend, setCanResend] = useState(false);
  const [isVerifying, setIsVerifying] = useState(false);

  useEffect(() => {
    if (countdown > 0) {
      const timer = setTimeout(() => setCountdown(countdown - 1), 1000);
      return () => clearTimeout(timer);
    } else {
      setCanResend(true);
    }
  }, [countdown]);

  const handleOtpChange = (index: number, value: string) => {
    if (value.length <= 1 && /^\d*$/.test(value)) {
      const newOtp = [...otp];
      newOtp[index] = value;
      setOtp(newOtp);

      // Auto-advance to next input
      if (value && index < 5) {
        const nextInput = document.getElementById(`otp-${index + 1}`);
        nextInput?.focus();
      }
    }
  };

  const handleKeyDown = (index: number, e: React.KeyboardEvent) => {
    if (e.key === "Backspace" && !otp[index] && index > 0) {
      const prevInput = document.getElementById(`otp-${index - 1}`);
      prevInput?.focus();
    }
  };

  const handlePaste = (e: React.ClipboardEvent) => {
    e.preventDefault();
    const pastedData = e.clipboardData.getData("text").slice(0, 6);
    if (/^\d{6}$/.test(pastedData)) {
      const newOtp = pastedData.split("");
      setOtp(newOtp);
      // Focus last input
      const lastInput = document.getElementById("otp-5");
      lastInput?.focus();
    }
  };

  const handleResend = () => {
    setCountdown(120);
    setCanResend(false);
    setOtp(["", "", "", "", "", ""]);
    // Focus first input
    const firstInput = document.getElementById("otp-0");
    firstInput?.focus();
  };

  const handleVerify = () => {
    setIsVerifying(true);
    // Simulate verification
    setTimeout(() => {
      setIsVerifying(false);
      // Navigate to success or next step
    }, 2000);
  };

  const isComplete = otp.every(digit => digit !== "");

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation Bar */}
      <nav className="bg-card border-b-2 border-border">
        <div className="max-w-[1400px] mx-auto px-8 py-4 flex items-center justify-between">
          <Link to="/patterns/identity" className="flex items-center gap-2 text-muted-foreground hover:text-primary">
            <ArrowLeft size={20} />
            <span className="font-medium">Back to Identity Patterns</span>
          </Link>
          <div className="text-sm text-muted-foreground">
            <span className="font-bold">Flow:</span> Email OTP Verification
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-[1400px] mx-auto px-8 py-12">
        <div className="grid grid-cols-12 gap-8">
          
          {/* Prototype View - 8 columns */}
          <div className="col-span-8">
            <div className="bg-card border-2 border-border rounded-lg overflow-hidden shadow-lg">
              {/* Tricolor Header */}
              <div className="bg-gradient-to-r from-orange-500 via-white to-green-500 h-2"></div>
              
              {/* Government Header */}
              <div className="bg-card border-b-2 border-border px-8 py-6">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-primary rounded flex items-center justify-center">
                    <Shield size={24} className="text-white" />
                  </div>
                  <div>
                    <div className="font-bold text-lg text-foreground">Digital India Portal</div>
                    <div className="text-sm text-muted-foreground">Government of India</div>
                  </div>
                </div>
              </div>

              {/* OTP Verification Content */}
              <div className="px-12 py-10">
                <div className="max-w-xl mx-auto text-center">
                  {/* Icon */}
                  <div className="w-20 h-20 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-6">
                    <Mail size={40} className="text-primary" />
                  </div>

                  {/* Heading */}
                  <h1 className="text-3xl font-bold text-foreground mb-3">Verify Your Email</h1>
                  <p className="text-muted-foreground mb-2">
                    We've sent a 6-digit verification code to
                  </p>
                  <p className="text-lg font-bold text-foreground mb-8">
                    user@example.com
                  </p>

                  {/* OTP Input */}
                  <div className="mb-8">
                    <label className="block text-sm font-bold text-foreground mb-4 text-left">
                      Enter 6-Digit Code <span className="text-red-600">*</span>
                    </label>
                    <div className="flex gap-3 justify-center" onPaste={handlePaste}>
                      {otp.map((digit, index) => (
                        <input
                          key={index}
                          id={`otp-${index}`}
                          type="text"
                          inputMode="numeric"
                          maxLength={1}
                          value={digit}
                          onChange={(e) => handleOtpChange(index, e.target.value)}
                          onKeyDown={(e) => handleKeyDown(index, e)}
                          className="w-16 h-16 text-center text-2xl font-bold border-2 border-border rounded-lg focus:border-primary focus:outline-none"
                          aria-label={`Digit ${index + 1}`}
                        />
                      ))}
                    </div>
                    <div className="text-sm text-muted-foreground mt-3 text-left">
                      <Info size={14} className="inline mr-1" />
                      You can paste the complete 6-digit code
                    </div>
                  </div>

                  {/* Timer/Resend */}
                  <div className="mb-8 p-4 bg-blue-50 border-2 border-blue-200 rounded-lg">
                    {!canResend ? (
                      <div className="flex items-center justify-center gap-2 text-sm text-muted-foreground">
                        <Clock size={16} className="text-blue-600" />
                        <span>
                          Code expires in <span className="font-bold">{Math.floor(countdown / 60)}:{String(countdown % 60).padStart(2, '0')}</span>
                        </span>
                      </div>
                    ) : (
                      <div className="text-sm text-muted-foreground">
                        Didn't receive the code?{" "}
                        <button
                          onClick={handleResend}
                          className="text-primary font-bold hover:underline"
                        >
                          Resend Code
                        </button>
                      </div>
                    )}
                  </div>

                  {/* Verify Button */}
                  <button
                    onClick={handleVerify}
                    disabled={!isComplete || isVerifying}
                    className="w-full py-4 bg-primary text-white font-bold rounded-lg hover:opacity-90 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors mb-6"
                  >
                    {isVerifying ? "Verifying..." : "Verify Email"}
                  </button>

                  {/* Help Text */}
                  <div className="text-sm text-muted-foreground text-left space-y-2">
                    <p className="flex items-start gap-2">
                      <Info size={14} className="flex-shrink-0 mt-0.5" />
                      <span>Check your spam/junk folder if you don't see the email</span>
                    </p>
                    <p className="flex items-start gap-2">
                      <Info size={14} className="flex-shrink-0 mt-0.5" />
                      <span>Email delivery may take up to 2 minutes</span>
                    </p>
                  </div>
                </div>
              </div>

              {/* Help Card */}
              <div className="border-t-2 border-border bg-background px-12 py-6">
                <div className="max-w-xl mx-auto">
                  <div className="flex items-start gap-3">
                    <HelpCircle size={20} className="text-primary flex-shrink-0 mt-0.5" />
                    <div>
                      <div className="font-bold text-foreground mb-2">Need Help?</div>
                      <div className="text-sm text-muted-foreground space-y-1">
                        <p>Call: <span className="font-bold">1800-XXX-XXXX</span> (Toll-Free)</p>
                        <p>Email: <span className="font-bold">support@digitalindia.gov.in</span></p>
                        <p className="text-muted-foreground">Monday to Friday, 9:00 AM - 6:00 PM IST</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Documentation Sidebar - 4 columns */}
          <aside className="col-span-4 space-y-6">
            <PatternInfo />
            <UserGoals />
            <ValidationRules />
            <AccessibilityNotes />
            <ImplementationNotes />
          </aside>

        </div>
      </main>
    </div>
  );
}

// ==================== SIDEBAR COMPONENTS ====================

function PatternInfo() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3">
        <h3 className="font-bold text-foreground">Pattern Info</h3>
      </div>
      <div className="p-4 space-y-3 text-sm">
        <InfoRow label="Pattern ID" value="UX4G-PAT-009-04" />
        <InfoRow label="Status" value="Stable" badge="green" />
        <InfoRow label="Complexity" value="Low" />
        <InfoRow label="Category" value="Verification" />
        <InfoRow label="Version" value="1.0.0" />
      </div>
    </div>
  );
}

function UserGoals() {
  return (
    <div className="border-2 border-blue-200 rounded-lg overflow-hidden bg-blue-50">
      <div className="bg-blue-100 border-b-2 border-blue-200 px-4 py-3">
        <h3 className="font-bold text-foreground">User Goals</h3>
      </div>
      <div className="p-4 space-y-2 text-sm text-muted-foreground">
        <GoalItem text="Verify email address quickly" />
        <GoalItem text="Receive OTP code reliably" />
        <GoalItem text="Understand expiry time" />
        <GoalItem text="Resend code if not received" />
        <GoalItem text="Get help if needed" />
      </div>
    </div>
  );
}

function ValidationRules() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3">
        <h3 className="font-bold text-foreground">Validation Rules</h3>
      </div>
      <div className="p-4 space-y-2 text-sm">
        <RuleItem text="OTP must be exactly 6 digits" />
        <RuleItem text="OTP valid for 2 minutes (120 seconds)" />
        <RuleItem text="Maximum 3 resend attempts" />
        <RuleItem text="After 3 failed verifications, lock for 15 minutes" />
        <RuleItem text="Support paste functionality for convenience" />
      </div>
    </div>
  );
}

function AccessibilityNotes() {
  return (
    <div className="border-2 border-green-200 rounded-lg overflow-hidden bg-green-50">
      <div className="bg-green-100 border-b-2 border-green-200 px-4 py-3">
        <h3 className="font-bold text-foreground">Accessibility</h3>
      </div>
      <div className="p-4 space-y-2 text-sm text-muted-foreground">
        <AccessibilityItem text="Each OTP input has aria-label" />
        <AccessibilityItem text="Countdown announced to screen readers" />
        <AccessibilityItem text="Paste support for assistive tech" />
        <AccessibilityItem text="Clear focus indicators on inputs" />
        <AccessibilityItem text="All buttons keyboard accessible" />
      </div>
    </div>
  );
}

function ImplementationNotes() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3">
        <h3 className="font-bold text-foreground">Implementation</h3>
      </div>
      <div className="p-4 space-y-3 text-sm text-muted-foreground">
        <div>
          <div className="font-bold text-foreground mb-1">Auto-advance</div>
          <div>Focus next input when digit entered</div>
        </div>
        <div>
          <div className="font-bold text-foreground mb-1">Paste support</div>
          <div>Accept 6-digit code paste from clipboard</div>
        </div>
        <div>
          <div className="font-bold text-foreground mb-1">Timer</div>
          <div>Use setInterval for countdown display</div>
        </div>
        <div>
          <div className="font-bold text-foreground mb-1">Rate limiting</div>
          <div>Block after 3 resend attempts (backend)</div>
        </div>
      </div>
    </div>
  );
}

// Helper Components
function InfoRow({ label, value, badge }: { label: string; value: string; badge?: string }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-muted-foreground">{label}</span>
      {badge ? (
        <span className={`px-2 py-0.5 ${badge === 'green' ? 'bg-green-100 text-green-700' : 'bg-muted text-muted-foreground'} text-xs font-bold rounded-full`}>
          {value}
        </span>
      ) : (
        <span className="font-bold text-foreground">{value}</span>
      )}
    </div>
  );
}

function GoalItem({ text }: { text: string }) {
  return (
    <div className="flex items-start gap-2">
      <CheckCircle size={14} className="text-blue-600 flex-shrink-0 mt-0.5" />
      <span>{text}</span>
    </div>
  );
}

function RuleItem({ text }: { text: string }) {
  return (
    <div className="flex items-start gap-2">
      <div className="w-1.5 h-1.5 bg-gray-400 rounded-full flex-shrink-0 mt-1.5"></div>
      <span className="text-muted-foreground">{text}</span>
    </div>
  );
}

function AccessibilityItem({ text }: { text: string }) {
  return (
    <div className="flex items-start gap-2">
      <CheckCircle size={14} className="text-green-600 flex-shrink-0 mt-0.5" />
      <span>{text}</span>
    </div>
  );
}

// src/app/angular-patterns-package/src/certificate-service/pages/identity-email-otp/identity-email-otp.component.ts
import { Component, ChangeDetectionStrategy, ElementRef, ViewChildren, QueryList } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ServiceHeaderComponent } from '../../../services/components/service-header/service-header.component';
import { ServiceFooterComponent } from '../../../services/components/service-footer/service-footer.component';

@Component({
  selector: 'identity-email-otp-page',
  standalone: true,
  imports: [CommonModule, FormsModule, ServiceHeaderComponent, ServiceFooterComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="eo">
      <div class="eo-tricolor" aria-hidden="true"></div>
      <header class="eo-gov">
        <span class="eo-gov__icon" aria-hidden="true">🛡️</span>
        <div><div class="eo-gov__title">Government of India</div><div class="eo-gov__sub">Unified Identity Service — Email Verification</div></div>
      </header>

      <main class="eo-main">
        <div class="eo-content">
          <div class="eo-form-col">
            <div class="eo-card">
              <div class="eo-card__icon" aria-hidden="true">📧</div>
              <h1 class="eo-card__title">Verify Your Email Address</h1>
              <p class="eo-card__desc">We've sent a 6-digit OTP to <strong>user@example.com</strong></p>

              <div class="eo-otp-group" role="group" aria-label="Enter 6-digit OTP">
                <input *ngFor="let d of digits; let i = index"
                  #otpInput
                  class="eo-otp-input"
                  type="text"
                  inputmode="numeric"
                  maxlength="1"
                  [attr.aria-label]="'Digit ' + (i + 1)"
                  [value]="digits[i]"
                  (input)="onDigitInput($event, i)"
                  (keydown)="onKeyDown($event, i)"
                />
              </div>

              <div class="eo-timer" aria-live="polite">
                <span *ngIf="countdown > 0">Resend OTP in <strong>{{ formattedTime }}</strong></span>
                <button *ngIf="countdown === 0" type="button" class="eo-resend" (click)="resendOtp()">Resend OTP</button>
              </div>

              <div class="eo-paste-hint">💡 Tip: You can paste the OTP code directly into the first field.</div>

              <button type="button" class="eo-btn eo-btn--primary" [disabled]="!isComplete" (click)="verify()">Verify &amp; Continue</button>

              <div class="eo-spam-tip">📬 Can't find the email? Check your spam or junk folder.</div>
            </div>
          </div>

          <aside class="eo-sidebar">
            <div class="eo-panel">
              <h2 class="eo-panel__title">Pattern Info</h2>
              <p class="eo-panel__text">Email OTP verification pattern with 2-minute expiry timer and auto-advance digit inputs.</p>
            </div>
            <div class="eo-panel">
              <h2 class="eo-panel__title">User Goals</h2>
              <ul class="eo-list">
                <li>Verify email ownership</li>
                <li>Complete registration flow</li>
                <li>Secure account with verified contact</li>
              </ul>
            </div>
            <div class="eo-panel">
              <h2 class="eo-panel__title">Validation Rules</h2>
              <ul class="eo-list">
                <li>6 numeric digits required</li>
                <li>2-minute expiry window</li>
                <li>Max 3 resend attempts</li>
                <li>Auto-submit on complete entry</li>
              </ul>
            </div>
            <div class="eo-panel">
              <h2 class="eo-panel__title">Accessibility Notes</h2>
              <ul class="eo-list">
                <li>Each input has unique aria-label</li>
                <li>Timer uses aria-live for updates</li>
                <li>Keyboard navigation between fields</li>
              </ul>
            </div>
            <div class="eo-panel">
              <h2 class="eo-panel__title">Implementation Notes</h2>
              <ul class="eo-list">
                <li>Paste support on first input</li>
                <li>Backspace navigates to previous</li>
                <li>Only numeric input accepted</li>
              </ul>
            </div>
          </aside>
        </div>
      </main>

      <ux4g-service-footer leftText="Unified Identity Service • Government of India" rightText="Email OTP Verification"></ux4g-service-footer>
    </div>
  `,
  styles: [`
    .eo { min-height: 100vh; background: var(--ux4g-svc-bg-muted, #f8fafc); font-family: system-ui, sans-serif; color: var(--ux4g-svc-fg, #0f172a); }
    .eo-tricolor { height: 4px; background: linear-gradient(to right, #ff9933 33%, #fff 33%, #fff 66%, #138808 66%); }
    .eo-gov { display: flex; align-items: center; gap: 0.75rem; padding: 1rem 2rem; background: var(--ux4g-svc-bg, #fff); border-bottom: 2px solid var(--ux4g-svc-border, #e2e8f0); }
    .eo-gov__icon { font-size: 1.75rem; }
    .eo-gov__title { font-weight: 700; font-size: 1rem; }
    .eo-gov__sub { font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); }
    .eo-main { max-width: 1200px; margin: 0 auto; padding: 2rem 1.5rem; }
    .eo-content { display: grid; grid-template-columns: 2fr 1fr; gap: 2rem; }
    .eo-form-col { max-width: 560px; }
    .eo-card { background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; padding: 2rem; text-align: center; }
    .eo-card__icon { font-size: 3rem; margin-bottom: 0.5rem; }
    .eo-card__title { font-size: 1.5rem; font-weight: 800; margin: 0 0 0.25rem; }
    .eo-card__desc { font-size: 0.875rem; color: var(--ux4g-svc-fg-muted, #64748b); margin: 0 0 2rem; }
    .eo-otp-group { display: flex; justify-content: center; gap: 0.75rem; margin-bottom: 1.5rem; }
    .eo-otp-input { width: 3rem; height: 3.5rem; text-align: center; font-size: 1.5rem; font-weight: 700; border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; }
    .eo-otp-input:focus { border-color: var(--ux4g-svc-primary, #4f46e5); outline: none; }
    .eo-timer { font-size: 0.875rem; color: var(--ux4g-svc-fg-muted, #64748b); margin-bottom: 1rem; }
    .eo-resend { background: none; border: none; color: var(--ux4g-svc-primary, #4f46e5); font-weight: 700; font-size: 0.875rem; cursor: pointer; text-decoration: underline; }
    .eo-paste-hint { font-size: 0.75rem; color: var(--ux4g-svc-fg-muted, #64748b); margin-bottom: 1.5rem; }
    .eo-btn { width: 100%; padding: 0.75rem; font-size: 0.875rem; font-weight: 700; border-radius: 0.375rem; border: none; cursor: pointer; }
    .eo-btn--primary { background: var(--ux4g-svc-primary, #4f46e5); color: #fff; }
    .eo-btn:disabled { background: #9ca3af; cursor: not-allowed; }
    .eo-spam-tip { font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); margin-top: 1.25rem; }
    .eo-sidebar { display: flex; flex-direction: column; gap: 1rem; }
    .eo-panel { background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; padding: 1.25rem; }
    .eo-panel__title { font-size: 0.875rem; font-weight: 700; margin: 0 0 0.75rem; }
    .eo-panel__text { font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); margin: 0; }
    .eo-list { margin: 0; padding-left: 1.25rem; font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); line-height: 1.8; }
    @media (max-width: 768px) {
      .eo-content { grid-template-columns: 1fr; }
      .eo-form-col { max-width: 100%; }
      .eo-otp-input { width: 2.5rem; height: 3rem; font-size: 1.25rem; }
    }
  `],
})
export class IdentityEmailOtpComponent {
  @ViewChildren('otpInput') otpInputs!: QueryList<ElementRef>;
  digits: string[] = ['', '', '', '', '', ''];
  countdown = 120;
  private timer: any;

  get isComplete(): boolean { return this.digits.every(d => d.length === 1); }

  get formattedTime(): string {
    const m = Math.floor(this.countdown / 60);
    const s = this.countdown % 60;
    return `${m}:${s.toString().padStart(2, '0')}`;
  }

  ngOnInit() { this.startTimer(); }
  ngOnDestroy() { clearInterval(this.timer); }

  startTimer() {
    this.countdown = 120;
    clearInterval(this.timer);
    this.timer = setInterval(() => { if (this.countdown > 0) this.countdown--; else clearInterval(this.timer); }, 1000);
  }

  onDigitInput(event: Event, index: number) {
    const input = event.target as HTMLInputElement;
    const val = input.value.replace(/\D/g, '');
    this.digits[index] = val.charAt(0) || '';
    input.value = this.digits[index];
    if (val && index < 5) {
      const inputs = this.otpInputs.toArray();
      inputs[index + 1]?.nativeElement.focus();
    }
  }

  onKeyDown(event: KeyboardEvent, index: number) {
    if (event.key === 'Backspace' && !this.digits[index] && index > 0) {
      const inputs = this.otpInputs.toArray();
      inputs[index - 1]?.nativeElement.focus();
    }
  }

  resendOtp() { this.digits = ['', '', '', '', '', '']; this.startTimer(); }
  verify() { if (this.isComplete) { /* navigate */ } }
}
