// src/app/react-core-package/src/components/Table/Table.tsx
/**
 * Table Component
 * Data table with sorting and filtering capabilities
 *
 * @example
 * ```tsx
 * <Table
 *   columns={[
 *     { key: 'name', header: 'Name', accessor: 'name', sortable: true },
 *     { key: 'email', header: 'Email', accessor: 'email' }
 *   ]}
 *   data={users}
 *   striped
 *   hoverable
 * />
 * ```
 */

import { ReactNode, useState, useMemo } from 'react';
import { cn } from '../../utils/cn';
import { TableProps, SortState, TableColumn } from './Table.types';

export function Table<T = any>({
  columns,
  data,
  rowKey,
  striped = false,
  hoverable = false,
  bordered = false,
  compact = false,
  caption,
  captionSide = 'top',
  sortState: controlledSortState,
  defaultSortState,
  onSortChange,
  onRowClick,
  emptyState,
  loading = false,
  loadingRows = 5,
  stickyHeader = false,
  maxHeight,
  className,
  ...props
}: TableProps<T>) {
  // Sort state management
  const [internalSortState, setInternalSortState] = useState<SortState>(
    defaultSortState || { columnKey: null, direction: null }
  );

  const sortState = controlledSortState ?? internalSortState;
  const isControlled = controlledSortState !== undefined;

  const handleSort = (column: TableColumn<T>) => {
    if (!column.sortable) return;

    const newSortState: SortState = {
      columnKey: column.key,
      direction:
        sortState.columnKey === column.key
          ? sortState.direction === 'asc'
            ? 'desc'
            : sortState.direction === 'desc'
            ? null
            : 'asc'
          : 'asc',
    };

    if (!isControlled) {
      setInternalSortState(newSortState);
    }
    onSortChange?.(newSortState);
  };

  // Sorted data
  const sortedData = useMemo(() => {
    if (!sortState.columnKey || !sortState.direction) {
      return data;
    }

    const column = columns.find((col) => col.key === sortState.columnKey);
    if (!column) return data;

    const sorted = [...data].sort((a, b) => {
      if (column.sortFn) {
        return column.sortFn(a, b);
      }

      const aValue = column.accessor
        ? typeof column.accessor === 'function'
          ? column.accessor(a)
          : a[column.accessor]
        : a[column.key as keyof T];

      const bValue = column.accessor
        ? typeof column.accessor === 'function'
          ? column.accessor(b)
          : b[column.accessor]
        : b[column.key as keyof T];

      if (aValue === bValue) return 0;
      if (aValue == null) return 1;
      if (bValue == null) return -1;

      if (typeof aValue === 'string' && typeof bValue === 'string') {
        return aValue.localeCompare(bValue);
      }

      return aValue < bValue ? -1 : 1;
    });

    return sortState.direction === 'desc' ? sorted.reverse() : sorted;
  }, [data, sortState, columns]);

  // Get row key
  const getRowKey = (row: T, index: number): string | number => {
    if (typeof rowKey === 'function') {
      return rowKey(row, index);
    }
    if (rowKey) {
      return row[rowKey] as string | number;
    }
    return index;
  };

  // Get cell value
  const getCellValue = (column: TableColumn<T>, row: T, index: number) => {
    if (column.render) {
      const value = column.accessor
        ? typeof column.accessor === 'function'
          ? column.accessor(row)
          : row[column.accessor]
        : row[column.key as keyof T];
      return column.render(value, row, index);
    }

    if (column.accessor) {
      return typeof column.accessor === 'function'
        ? column.accessor(row)
        : row[column.accessor];
    }

    return row[column.key as keyof T] as ReactNode;
  };

  // Render loading skeleton
  const renderLoadingSkeleton = () => (
    <tbody>
      {Array.from({ length: loadingRows }).map((_, index) => (
        <tr key={`skeleton-${index}`}>
          {columns.map((column) => (
            <td key={column.key} className="ux4g-table-cell">
              <div className="ux4g-skeleton ux4g-skeleton-text" />
            </td>
          ))}
        </tr>
      ))}
    </tbody>
  );

  // Render empty state
  const renderEmptyState = () => (
    <tbody>
      <tr>
        <td colSpan={columns.length} className="ux4g-table-empty">
          {emptyState || 'No data available'}
        </td>
      </tr>
    </tbody>
  );

  const containerStyle = maxHeight ? { maxHeight, overflow: 'auto' } : undefined;

  const getAriaSort = (column: TableColumn<T>) => {
    if (!column.sortable) return undefined;
    if (sortState.columnKey !== column.key || !sortState.direction) {
      return 'none';
    }
    return sortState.direction === 'asc' ? 'ascending' : 'descending';
  };

  return (
    <div
      className={cn('ux4g-table-container', className)}
      style={containerStyle}
      aria-busy={loading || undefined}
      {...props}
    >
      <table
        className={cn(
          'ux4g-table',
          striped && 'ux4g-table-striped',
          hoverable && 'ux4g-table-hoverable',
          bordered && 'ux4g-table-bordered',
          compact && 'ux4g-table-compact',
          stickyHeader && 'ux4g-table-sticky-header'
        )}
      >
        {caption && (
          <caption
            className={cn(
              'ux4g-table-caption',
              `ux4g-table-caption-${captionSide}`
            )}
          >
            {caption}
          </caption>
        )}
        <thead className="ux4g-table-header">
          <tr>
            {columns.map((column) => (
              <th
                key={column.key}
                scope="col"
                className={cn(
                  'ux4g-table-header-cell',
                  column.sortable && 'ux4g-table-header-sortable',
                  column.align && `ux4g-text-${column.align}`,
                  sortState.columnKey === column.key && 'ux4g-table-header-sorted'
                )}
                style={column.width ? { width: column.width } : undefined}
                aria-sort={getAriaSort(column)}
                {...column.headerProps}
              >
                {column.sortable ? (
                  <button
                    type="button"
                    className="ux4g-table-header-button"
                    onClick={() => handleSort(column)}
                  >
                    <span className="ux4g-table-header-content">
                      {column.header}
                      <span className="ux4g-table-sort-icon" aria-hidden="true">
                        {sortState.columnKey === column.key
                          ? sortState.direction === 'asc'
                            ? '↑'
                            : sortState.direction === 'desc'
                            ? '↓'
                            : '↕'
                          : '↕'}
                      </span>
                    </span>
                    <span className="sr-only">
                      {sortState.columnKey === column.key && sortState.direction
                        ? `Sorted ${sortState.direction === 'asc' ? 'ascending' : 'descending'}`
                        : 'Not sorted'}
                    </span>
                  </button>
                ) : (
                  <div className="ux4g-table-header-content">{column.header}</div>
                )}
              </th>
            ))}
          </tr>
        </thead>
        {loading ? (
          renderLoadingSkeleton()
        ) : sortedData.length === 0 ? (
          renderEmptyState()
        ) : (
          <tbody className="ux4g-table-body">
            {sortedData.map((row, index) => (
              <tr
                key={getRowKey(row, index)}
                className={cn(
                  'ux4g-table-row',
                  onRowClick && 'ux4g-table-row-clickable'
                )}
                onClick={() => onRowClick?.(row, index)}
                onKeyDown={(event) => {
                  if (!onRowClick) return;
                  if (event.key === 'Enter' || event.key === ' ') {
                    event.preventDefault();
                    onRowClick(row, index);
                  }
                }}
                tabIndex={onRowClick ? 0 : undefined}
              >
                {columns.map((column) => (
                  <td
                    key={column.key}
                    className={cn(
                      'ux4g-table-cell',
                      column.align && `ux4g-text-${column.align}`
                    )}
                    {...column.cellProps}
                  >
                    {getCellValue(column, row, index)}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        )}
      </table>
    </div>
  );
}

Table.displayName = 'Table';

// src/app/angular-core-package/src/lib/table/table.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
  ViewEncapsulation,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { classNames } from '../../utils/class-names';

export interface TableColumn {
  key: string;
  label: string;
  sortable?: boolean;
  width?: string;
  align?: 'left' | 'center' | 'right';
}

export interface TableSortEvent {
  column: string;
  direction: 'asc' | 'desc';
}

/**
 * UX4G Table Component
 *
 * A data table component with sorting, striping, and hover effects.
 * Supports custom column configuration and row templates.
 * Follows WCAG 2.1 Level AA accessibility standards.
 *
 * @example
 * <ux4g-table
 *   [columns]="columns"
 *   [data]="data"
 *   [striped]="true"
 *   [hoverable]="true"
 * ></ux4g-table>
 *
 * @example
 * <ux4g-table
 *   [columns]="columns"
 *   [data]="users"
 *   [sortable]="true"
 *   (sorted)="handleSort($event)"
 * ></ux4g-table>
 */
@Component({
  selector: 'ux4g-table',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div [class]="wrapperClasses">
      <table [class]="tableClasses" [attr.data-testid]="testId">
        @if (caption) {
          <caption [class]="captionClasses">{{ caption }}</caption>
        }

        <thead [class]="theadClasses">
          <tr>
            @for (column of columns; track column.key) {
              <th
                [class]="getHeaderClasses(column)"
                [style.width]="column.width"
                [attr.scope]="'col'"
                [attr.aria-sort]="getAriaSort(column.key)"
              >
                @if (sortable && column.sortable !== false) {
                  <button
                    type="button"
                    class="ux4g-table__sort-button"
                    (click)="handleSort(column.key)"
                  >
                    {{ column.label }}
                    <span class="ux4g-table__sort-icon" aria-hidden="true">
                      @if (sortColumn === column.key) {
                        @if (sortDirection === 'asc') {
                          ↑
                        } @else {
                          ↓
                        }
                      } @else {
                        ↕
                      }
                    </span>
                  </button>
                } @else {
                  {{ column.label }}
                }
              </th>
            }
          </tr>
        </thead>

        <tbody [class]="tbodyClasses">
          @if (data && data.length > 0) {
            @for (row of data; track trackByFn($index, row); let i = $index) {
              <tr [class]="getRowClasses(i)" (click)="handleRowClick(row, i)">
                @for (column of columns; track column.key) {
                  <td [class]="getCellClasses(column)">
                    {{ getCellValue(row, column.key) }}
                  </td>
                }
              </tr>
            }
          } @else {
            <tr>
              <td [attr.colspan]="columns.length" class="ux4g-table__empty">
                {{ emptyMessage }}
              </td>
            </tr>
          }
        </tbody>

        @if (showFooter) {
          <tfoot [class]="tfootClasses">
            <ng-content select="[slot='footer']"></ng-content>
          </tfoot>
        }
      </table>
    </div>
  `,
  styleUrls: ['./table.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export class TableComponent {
  /**
   * Table columns configuration
   */
  @Input() columns: TableColumn[] = [];

  /**
   * Table data rows
   */
  @Input() data: any[] = [];

  /**
   * Table caption for accessibility
   */
  @Input() caption?: string;

  /**
   * Whether to show caption visually
   * @default false
   */
  @Input() showCaption: boolean = false;

  /**
   * Whether the table is sortable
   * @default false
   */
  @Input() sortable: boolean = false;

  /**
   * Whether to show striped rows
   * @default false
   */
  @Input() striped: boolean = false;

  /**
   * Whether to show hover effect on rows
   * @default false
   */
  @Input() hoverable: boolean = false;

  /**
   * Whether the table is bordered
   * @default true
   */
  @Input() bordered: boolean = true;

  /**
   * Whether to make the table compact
   * @default false
   */
  @Input() compact: boolean = false;

  /**
   * Whether rows are clickable
   * @default false
   */
  @Input() clickableRows: boolean = false;

  /**
   * Whether to show footer
   * @default false
   */
  @Input() showFooter: boolean = false;

  /**
   * Message to show when table is empty
   * @default 'No data available'
   */
  @Input() emptyMessage: string = 'No data available';

  /**
   * Custom track by function for row rendering
   */
  @Input() trackByFn: (index: number, item: any) => any = (index) => index;

  /**
   * Additional CSS classes
   */
  @Input() className?: string;

  /**
   * Test identifier
   */
  @Input() testId?: string;

  /**
   * Sort event emitter
   */
  @Output() sorted = new EventEmitter<TableSortEvent>();

  /**
   * Row click event emitter
   */
  @Output() rowClicked = new EventEmitter<{ row: any; index: number }>();

  /**
   * Current sort column
   */
  sortColumn: string | null = null;

  /**
   * Current sort direction
   */
  sortDirection: 'asc' | 'desc' = 'asc';

  /**
   * Computed wrapper classes
   */
  get wrapperClasses(): string {
    return classNames('ux4g-table-wrapper', this.className);
  }

  /**
   * Computed table classes
   */
  get tableClasses(): string {
    return classNames(
      'ux4g-table',
      this.bordered && 'ux4g-table--bordered',
      this.striped && 'ux4g-table--striped',
      this.hoverable && 'ux4g-table--hoverable',
      this.compact && 'ux4g-table--compact',
      this.clickableRows && 'ux4g-table--clickable-rows'
    );
  }

  /**
   * Computed caption classes
   */
  get captionClasses(): string {
    return classNames(
      'ux4g-table__caption',
      !this.showCaption && 'sr-only'
    );
  }

  /**
   * Computed thead classes
   */
  get theadClasses(): string {
    return classNames('ux4g-table__thead');
  }

  /**
   * Computed tbody classes
   */
  get tbodyClasses(): string {
    return classNames('ux4g-table__tbody');
  }

  /**
   * Computed tfoot classes
   */
  get tfootClasses(): string {
    return classNames('ux4g-table__tfoot');
  }

  /**
   * Get header cell classes
   */
  getHeaderClasses(column: TableColumn): string {
    return classNames(
      'ux4g-table__th',
      column.align && 'ux4g-table__th--' + column.align,
      this.sortable && column.sortable !== false && 'ux4g-table__th--sortable',
      this.sortColumn === column.key && 'ux4g-table__th--sorted'
    );
  }

  /**
   * Get cell classes
   */
  getCellClasses(column: TableColumn): string {
    return classNames(
      'ux4g-table__td',
      column.align && 'ux4g-table__td--' + column.align
    );
  }

  /**
   * Get row classes
   */
  getRowClasses(index: number): string {
    return classNames(
      'ux4g-table__tr',
      this.clickableRows && 'ux4g-table__tr--clickable'
    );
  }

  /**
   * Get ARIA sort value
   */
  getAriaSort(columnKey: string): string | null {
    if (!this.sortable || this.sortColumn !== columnKey) {
      return null;
    }
    return this.sortDirection === 'asc' ? 'ascending' : 'descending';
  }

  /**
   * Get cell value from row data
   */
  getCellValue(row: any, key: string): any {
    const keys = key.split('.');
    let value = row;
    for (const k of keys) {
      value = value?.[k];
    }
    return value ?? '';
  }

  /**
   * Handle sort click
   */
  handleSort(columnKey: string): void {
    if (!this.sortable) {
      return;
    }

    if (this.sortColumn === columnKey) {
      this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      this.sortColumn = columnKey;
      this.sortDirection = 'asc';
    }

    this.sorted.emit({
      column: columnKey,
      direction: this.sortDirection,
    });
  }

  /**
   * Handle row click
   */
  handleRowClick(row: any, index: number): void {
    if (this.clickableRows) {
      this.rowClicked.emit({ row, index });
    }
  }
}
