// src/app/pages/IdentitySessionTimeout.tsx
import { Link } from "react-router";
import { ArrowLeft, Shield, Clock, AlertCircle, RefreshCw, Info, HelpCircle, CheckCircle } from "lucide-react";
import { useState, useEffect } from "react";

export default function IdentitySessionTimeout() {
  const [timeLeft, setTimeLeft] = useState(120); // 2 minutes warning
  const [showWarning, setShowWarning] = useState(true);
  const [timedOut, setTimedOut] = useState(false);

  useEffect(() => {
    if (showWarning && timeLeft > 0) {
      const timer = setTimeout(() => setTimeLeft(timeLeft - 1), 1000);
      return () => clearTimeout(timer);
    } else if (timeLeft === 0) {
      setTimedOut(true);
      setShowWarning(false);
    }
  }, [timeLeft, showWarning]);

  const handleStayLoggedIn = () => {
    setShowWarning(false);
    setTimeLeft(120);
    // Refresh session on backend
  };

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${String(secs).padStart(2, '0')}`;
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation Bar */}
      <nav className="bg-card border-b-2 border-border">
        <div className="max-w-[1400px] mx-auto px-8 py-4 flex items-center justify-between">
          <Link to="/patterns/identity" className="flex items-center gap-2 text-muted-foreground hover:text-primary">
            <ArrowLeft size={20} />
            <span className="font-medium">Back to Identity Patterns</span>
          </Link>
          <div className="text-sm text-muted-foreground">
            <span className="font-bold">Flow:</span> Session Timeout / Re-authentication
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-[1400px] mx-auto px-8 py-12">
        <div className="grid grid-cols-12 gap-8">
          
          {/* Prototype View - 8 columns */}
          <div className="col-span-8">
            <div className="bg-card border-2 border-border rounded-lg overflow-hidden shadow-lg">
              {/* Tricolor Header */}
              <div className="bg-gradient-to-r from-orange-500 via-white to-green-500 h-2"></div>
              
              {/* Government Header */}
              <div className="bg-card border-b-2 border-border px-8 py-6">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-primary rounded flex items-center justify-center">
                    <Shield size={24} className="text-white" />
                  </div>
                  <div>
                    <div className="font-bold text-lg text-foreground">Digital India Portal</div>
                    <div className="text-sm text-muted-foreground">Government of India</div>
                  </div>
                </div>
              </div>

              {/* Session Warning Modal Overlay */}
              {showWarning && (
                <div className="relative">
                  {/* Dimmed Background */}
                  <div className="absolute inset-0 bg-gray-900/50 z-10"></div>
                  
                  {/* Warning Modal */}
                  <div className="absolute inset-0 flex items-center justify-center z-20 p-12">
                    <div className="bg-card border-2 border-yellow-300 rounded-lg shadow-2xl max-w-lg w-full">
                      <div className="bg-yellow-100 border-b-2 border-yellow-300 px-6 py-4 flex items-center gap-3">
                        <Clock size={24} className="text-yellow-700" />
                        <h2 className="font-bold text-foreground text-lg">Session About to Expire</h2>
                      </div>
                      
                      <div className="p-6 text-center">
                        <div className="w-24 h-24 bg-yellow-100 rounded-full flex items-center justify-center mx-auto mb-6">
                          <div className="text-5xl font-bold text-yellow-700">{formatTime(timeLeft)}</div>
                        </div>
                        
                        <p className="text-muted-foreground mb-6 leading-relaxed">
                          Your session will expire due to inactivity. You'll be automatically logged out for security reasons.
                        </p>

                        <div className="space-y-3">
                          <button
                            onClick={handleStayLoggedIn}
                            className="w-full py-4 bg-primary text-white font-bold rounded-lg hover:opacity-90 transition-colors"
                          >
                            Stay Logged In
                          </button>
                          <button
                            onClick={() => setTimedOut(true)}
                            className="w-full py-3 bg-card text-muted-foreground font-medium border-2 border-border rounded-lg hover:bg-background transition-colors"
                          >
                            Log Out Now
                          </button>
                        </div>

                        <div className="mt-6 p-4 bg-blue-50 border-2 border-blue-200 rounded-lg text-sm text-left">
                          <div className="flex items-start gap-2">
                            <Info size={16} className="text-blue-600 flex-shrink-0 mt-0.5" />
                            <div className="text-muted-foreground">
                              <div className="font-bold text-foreground mb-1">Why does this happen?</div>
                              <p>Sessions expire after 30 minutes of inactivity to protect your account and data.</p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* Timed Out View */}
              {timedOut && (
                <div className="px-12 py-16">
                  <div className="max-w-xl mx-auto text-center">
                    <div className="w-20 h-20 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-6">
                      <AlertCircle size={40} className="text-red-600" />
                    </div>
                    
                    <h1 className="text-3xl font-bold text-foreground mb-3">Session Expired</h1>
                    <p className="text-muted-foreground mb-8">
                      Your session has expired due to inactivity. For security, you've been logged out automatically.
                    </p>

                    <div className="p-6 bg-muted border-2 border-border rounded-lg mb-8 text-left">
                      <div className="font-bold text-foreground mb-3">Your work has been saved</div>
                      <div className="text-sm text-muted-foreground space-y-2">
                        <p>• Any form data you entered has been saved as a draft</p>
                        <p>• Simply sign in again to continue where you left off</p>
                        <p>• Your draft will be available for 24 hours</p>
                      </div>
                    </div>

                    <Link
                      to="/patterns/identity/sign-in"
                      className="block w-full py-4 bg-primary text-white font-bold rounded-lg hover:opacity-90 transition-colors text-center mb-4"
                    >
                      Sign In Again
                    </Link>

                    <div className="text-sm text-muted-foreground">
                      <Info size={14} className="inline mr-1" />
                      Session timeout helps protect your account from unauthorized access
                    </div>
                  </div>
                </div>
              )}

              {/* Active Session View (when warning dismissed) */}
              {!showWarning && !timedOut && (
                <div className="px-12 py-16">
                  <div className="max-w-xl mx-auto text-center">
                    <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
                      <CheckCircle size={40} className="text-green-600" />
                    </div>
                    
                    <h1 className="text-3xl font-bold text-foreground mb-3">Session Extended</h1>
                    <p className="text-muted-foreground mb-8">
                      Your session has been extended. You can continue working without interruption.
                    </p>

                    <div className="p-6 bg-blue-50 border-2 border-blue-200 rounded-lg mb-8 text-left">
                      <div className="font-bold text-foreground mb-3">Session Security</div>
                      <div className="text-sm text-muted-foreground space-y-2">
                        <p>• Sessions expire after 30 minutes of inactivity</p>
                        <p>• You'll receive a warning 2 minutes before expiry</p>
                        <p>• Maximum session duration: 8 hours</p>
                        <p>• Always log out when finished for security</p>
                      </div>
                    </div>

                    <button
                      onClick={() => setShowWarning(true)}
                      className="w-full py-3 bg-card text-muted-foreground font-medium border-2 border-border rounded-lg hover:bg-background transition-colors"
                    >
                      <RefreshCw size={16} className="inline mr-2" />
                      View Session Warning Again
                    </button>
                  </div>
                </div>
              )}

              {/* Help Card */}
              <div className="border-t-2 border-border bg-background px-12 py-6">
                <div className="max-w-xl mx-auto">
                  <div className="flex items-start gap-3">
                    <HelpCircle size={20} className="text-primary flex-shrink-0 mt-0.5" />
                    <div>
                      <div className="font-bold text-foreground mb-2">Need Help?</div>
                      <div className="text-sm text-muted-foreground space-y-1">
                        <p>Call: <span className="font-bold">1800-XXX-XXXX</span> (Toll-Free)</p>
                        <p>Email: <span className="font-bold">support@digitalindia.gov.in</span></p>
                        <p className="text-muted-foreground">Monday to Friday, 9:00 AM - 6:00 PM IST</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Documentation Sidebar - 4 columns */}
          <aside className="col-span-4 space-y-6">
            <PatternInfo />
            <SecurityRationale />
            <TimingConfiguration />
            <ImplementationNotes />
          </aside>

        </div>
      </main>
    </div>
  );
}

// ==================== SIDEBAR COMPONENTS ====================

function PatternInfo() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3">
        <h3 className="font-bold text-foreground">Pattern Info</h3>
      </div>
      <div className="p-4 space-y-3 text-sm">
        <InfoRow label="Pattern ID" value="UX4G-PAT-009-08" />
        <InfoRow label="Status" value="Stable" badge="green" />
        <InfoRow label="Complexity" value="Medium" />
        <InfoRow label="Category" value="Security" />
        <InfoRow label="Version" value="1.0.0" />
      </div>
    </div>
  );
}

function SecurityRationale() {
  return (
    <div className="border-2 border-red-200 rounded-lg overflow-hidden bg-red-50">
      <div className="bg-red-100 border-b-2 border-red-200 px-4 py-3">
        <h3 className="font-bold text-foreground">Security Rationale</h3>
      </div>
      <div className="p-4 space-y-2 text-sm text-muted-foreground">
        <SecurityItem text="Prevents unauthorized access to unattended devices" />
        <SecurityItem text="Reduces risk of session hijacking" />
        <SecurityItem text="Protects sensitive government data" />
        <SecurityItem text="Complies with security standards" />
        <SecurityItem text="Mandatory for high-security services" />
      </div>
    </div>
  );
}

function TimingConfiguration() {
  return (
    <div className="border-2 border-border rounded-lg overflow-hidden bg-card">
      <div className="bg-muted border-b-2 border-border px-4 py-3">
        <h3 className="font-bold text-foreground">Timing Configuration</h3>
      </div>
      <div className="p-4 space-y-3 text-sm">
        <ConfigItem label="Inactivity Timeout" value="30 minutes" />
        <ConfigItem label="Warning Time" value="2 minutes before" />
        <ConfigItem label="Max Session" value="8 hours" />
        <ConfigItem label="Countdown Interval" value="1 second" />
      </div>
    </div>
  );
}

function ImplementationNotes() {
  return (
    <div className="border-2 border-blue-200 rounded-lg overflow-hidden bg-blue-50">
      <div className="bg-blue-100 border-b-2 border-blue-200 px-4 py-3">
        <h3 className="font-bold text-foreground">Implementation</h3>
      </div>
      <div className="p-4 space-y-3 text-sm text-muted-foreground">
        <ImplementationItem
          title="Idle Detection"
          description="Track mouse movement, keyboard input, scroll events"
        />
        <ImplementationItem
          title="Warning Modal"
          description="Show modal overlay 2 minutes before expiry with countdown"
        />
        <ImplementationItem
          title="Session Extension"
          description="Refresh session token on backend when user clicks 'Stay Logged In'"
        />
        <ImplementationItem
          title="Auto-logout"
          description="Clear session and redirect to login when timer reaches zero"
        />
      </div>
    </div>
  );
}

// Helper Components
function InfoRow({ label, value, badge }: { label: string; value: string; badge?: string }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-muted-foreground">{label}</span>
      {badge ? (
        <span className={`px-2 py-0.5 ${badge === 'green' ? 'bg-green-100 text-green-700' : 'bg-muted text-muted-foreground'} text-xs font-bold rounded-full`}>
          {value}
        </span>
      ) : (
        <span className="font-bold text-foreground">{value}</span>
      )}
    </div>
  );
}

function SecurityItem({ text }: { text: string }) {
  return (
    <div className="flex items-start gap-2">
      <AlertCircle size={14} className="text-red-600 flex-shrink-0 mt-0.5" />
      <span>{text}</span>
    </div>
  );
}

function ConfigItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-muted-foreground">{label}</span>
      <span className="font-bold text-foreground">{value}</span>
    </div>
  );
}

function ImplementationItem({ title, description }: { title: string; description: string }) {
  return (
    <div>
      <div className="font-bold text-foreground mb-1">{title}</div>
      <div className="text-xs text-muted-foreground">{description}</div>
    </div>
  );
}

// src/app/angular-patterns-package/src/certificate-service/pages/identity-session-timeout/identity-session-timeout.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ServiceHeaderComponent } from '../../../services/components/service-header/service-header.component';
import { ServiceFooterComponent } from '../../../services/components/service-footer/service-footer.component';

@Component({
  selector: 'identity-session-timeout-page',
  standalone: true,
  imports: [CommonModule, ServiceHeaderComponent, ServiceFooterComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="st">
      <div class="st-tricolor" aria-hidden="true"></div>
      <header class="st-gov">
        <span class="st-gov__icon" aria-hidden="true">🛡️</span>
        <div><div class="st-gov__title">Government of India</div><div class="st-gov__sub">Unified Identity Service — Session Management</div></div>
      </header>

      <main class="st-main">
        <div class="st-content">
          <div class="st-form-col">
            <!-- State Selector -->
            <div class="st-selector">
              <button *ngFor="let s of states" type="button" class="st-sel-btn" [class.st-sel-btn--active]="state === s.key" (click)="state = s.key">{{ s.label }}</button>
            </div>

            <!-- Warning State -->
            <div *ngIf="state === 'warning'" class="st-overlay" role="dialog" aria-modal="true" aria-label="Session timeout warning">
              <div class="st-modal">
                <div class="st-modal__icon" aria-hidden="true">⏰</div>
                <h1 class="st-modal__title">Session Expiring Soon</h1>
                <p class="st-modal__desc">Your session will expire due to inactivity. Any unsaved work will be preserved.</p>
                <div class="st-countdown" aria-live="polite">
                  <div class="st-countdown__time">{{ formattedTime }}</div>
                  <div class="st-countdown__label">Time Remaining</div>
                </div>
                <div class="st-modal__actions">
                  <button type="button" class="st-btn st-btn--primary" (click)="state = 'extended'">Stay Logged In</button>
                  <button type="button" class="st-btn st-btn--outline" (click)="state = 'expired'">Log Out Now</button>
                </div>
                <p class="st-modal__explain">For your security, sessions automatically expire after 15 minutes of inactivity.</p>
              </div>
            </div>

            <!-- Timed Out State -->
            <div *ngIf="state === 'expired'" class="st-card st-card--expired">
              <div class="st-card__icon" aria-hidden="true">🔒</div>
              <h1 class="st-card__title">Session Expired</h1>
              <p class="st-card__desc">Your session has timed out due to inactivity.</p>
              <div class="st-notice">
                <span aria-hidden="true">💾</span> Your work has been saved. You can continue where you left off after signing in.
              </div>
              <a class="st-btn st-btn--primary" href="/reference-service/certificate/identity/sign-in">Sign In Again</a>
            </div>

            <!-- Extended State -->
            <div *ngIf="state === 'extended'" class="st-card st-card--extended">
              <div class="st-card__icon" aria-hidden="true">✅</div>
              <h1 class="st-card__title">Session Extended</h1>
              <p class="st-card__desc">Your session has been extended successfully. You can continue working.</p>
              <div class="st-session-info">
                <div class="st-session-info__row"><span>Session Status</span><span class="st-badge st-badge--green">Active</span></div>
                <div class="st-session-info__row"><span>Last Activity</span><span>Just now</span></div>
                <div class="st-session-info__row"><span>Session Timeout</span><span>15 minutes of inactivity</span></div>
                <div class="st-session-info__row"><span>Maximum Duration</span><span>8 hours</span></div>
              </div>
            </div>
          </div>

          <aside class="st-sidebar">
            <div class="st-panel"><h2 class="st-panel__title">Pattern Info</h2><p class="st-panel__text">Session timeout pattern with warning modal, expired state, and extension confirmation. Protects user data while maintaining security.</p></div>
            <div class="st-panel"><h2 class="st-panel__title">Security Rationale</h2>
              <ul class="st-list"><li>Prevents unauthorized access on shared devices</li><li>Complies with government security standards</li><li>Auto-saves work before expiry</li></ul>
            </div>
            <div class="st-panel"><h2 class="st-panel__title">Timing Configuration</h2>
              <ul class="st-list"><li>Idle timeout: 15 minutes</li><li>Warning shown: 2 minutes before</li><li>Max session: 8 hours</li><li>Extension adds: 15 minutes</li></ul>
            </div>
            <div class="st-panel"><h2 class="st-panel__title">Implementation Notes</h2>
              <ul class="st-list"><li>Uses requestAnimationFrame for timer</li><li>Heartbeat API to extend server session</li><li>localStorage for cross-tab sync</li><li>Focus trap in warning modal</li></ul>
            </div>
          </aside>
        </div>
      </main>

      <ux4g-service-footer leftText="Unified Identity Service • Government of India" rightText="Session Management"></ux4g-service-footer>
    </div>
  `,
  styles: [`
    .st { min-height: 100vh; background: var(--ux4g-svc-bg-muted, #f8fafc); font-family: system-ui, sans-serif; color: var(--ux4g-svc-fg, #0f172a); }
    .st-tricolor { height: 4px; background: linear-gradient(to right, #ff9933 33%, #fff 33%, #fff 66%, #138808 66%); }
    .st-gov { display: flex; align-items: center; gap: 0.75rem; padding: 1rem 2rem; background: var(--ux4g-svc-bg, #fff); border-bottom: 2px solid var(--ux4g-svc-border, #e2e8f0); }
    .st-gov__icon { font-size: 1.75rem; }
    .st-gov__title { font-weight: 700; font-size: 1rem; }
    .st-gov__sub { font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); }
    .st-main { max-width: 1200px; margin: 0 auto; padding: 2rem 1.5rem; }
    .st-content { display: grid; grid-template-columns: 2fr 1fr; gap: 2rem; }
    .st-form-col { max-width: 600px; }
    .st-selector { display: flex; gap: 0.5rem; margin-bottom: 1.5rem; flex-wrap: wrap; }
    .st-sel-btn { padding: 0.5rem 1rem; font-size: 0.8125rem; font-weight: 700; border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.375rem; background: var(--ux4g-svc-bg, #fff); cursor: pointer; }
    .st-sel-btn--active { border-color: var(--ux4g-svc-primary, #4f46e5); background: #eff6ff; color: var(--ux4g-svc-primary, #4f46e5); }
    .st-overlay { background: rgba(0,0,0,0.5); border-radius: 0.5rem; padding: 2rem; display: flex; align-items: center; justify-content: center; min-height: 400px; }
    .st-modal { background: var(--ux4g-svc-bg, #fff); border-radius: 0.75rem; padding: 2.5rem; text-align: center; max-width: 420px; width: 100%; box-shadow: 0 20px 60px rgba(0,0,0,0.15); }
    .st-modal__icon { font-size: 3rem; margin-bottom: 0.5rem; }
    .st-modal__title { font-size: 1.375rem; font-weight: 800; margin: 0 0 0.5rem; }
    .st-modal__desc { font-size: 0.875rem; color: var(--ux4g-svc-fg-muted, #64748b); margin: 0 0 1.5rem; }
    .st-countdown { margin-bottom: 1.5rem; }
    .st-countdown__time { font-size: 2.5rem; font-weight: 800; color: #dc2626; font-family: monospace; }
    .st-countdown__label { font-size: 0.75rem; color: var(--ux4g-svc-fg-muted, #64748b); }
    .st-modal__actions { display: flex; flex-direction: column; gap: 0.75rem; margin-bottom: 1rem; }
    .st-modal__explain { font-size: 0.75rem; color: var(--ux4g-svc-fg-muted, #64748b); margin: 0; }
    .st-card { background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; padding: 2.5rem; text-align: center; }
    .st-card--expired { border-color: #fca5a5; }
    .st-card--extended { border-color: #86efac; }
    .st-card__icon { font-size: 3rem; margin-bottom: 0.5rem; }
    .st-card__title { font-size: 1.5rem; font-weight: 800; margin: 0 0 0.25rem; }
    .st-card__desc { font-size: 0.875rem; color: var(--ux4g-svc-fg-muted, #64748b); margin: 0 0 1.5rem; }
    .st-notice { background: #f0fdf4; border: 1px solid #86efac; border-radius: 0.375rem; padding: 0.875rem; font-size: 0.8125rem; margin-bottom: 1.5rem; text-align: left; }
    .st-btn { display: block; width: 100%; padding: 0.75rem; font-size: 0.875rem; font-weight: 700; border-radius: 0.375rem; border: none; cursor: pointer; text-align: center; text-decoration: none; }
    .st-btn--primary { background: var(--ux4g-svc-primary, #4f46e5); color: #fff; }
    .st-btn--outline { background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); color: var(--ux4g-svc-fg, #0f172a); }
    .st-session-info { border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.375rem; overflow: hidden; text-align: left; }
    .st-session-info__row { display: flex; justify-content: space-between; padding: 0.75rem 1rem; font-size: 0.875rem; border-bottom: 1px solid var(--ux4g-svc-border, #e2e8f0); }
    .st-session-info__row:last-child { border-bottom: none; }
    .st-session-info__row:nth-child(even) { background: var(--ux4g-svc-bg-muted, #f8fafc); }
    .st-badge { display: inline-block; padding: 0.125rem 0.5rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 700; }
    .st-badge--green { background: #dcfce7; color: #16a34a; }
    .st-sidebar { display: flex; flex-direction: column; gap: 1rem; }
    .st-panel { background: var(--ux4g-svc-bg, #fff); border: 2px solid var(--ux4g-svc-border, #e2e8f0); border-radius: 0.5rem; padding: 1.25rem; }
    .st-panel__title { font-size: 0.875rem; font-weight: 700; margin: 0 0 0.75rem; }
    .st-panel__text { font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); margin: 0; }
    .st-list { margin: 0; padding-left: 1.25rem; font-size: 0.8125rem; color: var(--ux4g-svc-fg-muted, #64748b); line-height: 1.8; }
    @media (max-width: 768px) {
      .st-content { grid-template-columns: 1fr; }
      .st-form-col { max-width: 100%; }
    }
  `],
})
export class IdentitySessionTimeoutComponent {
  state: 'warning' | 'expired' | 'extended' = 'warning';
  countdown = 120;
  private timer: any;

  states = [
    { key: 'warning' as const, label: '⏰ Warning' },
    { key: 'expired' as const, label: '🔒 Timed Out' },
    { key: 'extended' as const, label: '✅ Extended' },
  ];

  get formattedTime(): string {
    const m = Math.floor(this.countdown / 60);
    const s = this.countdown % 60;
    return `${m}:${s.toString().padStart(2, '0')}`;
  }

  ngOnInit() { this.startTimer(); }
  ngOnDestroy() { clearInterval(this.timer); }

  startTimer() {
    this.countdown = 120;
    clearInterval(this.timer);
    this.timer = setInterval(() => {
      if (this.countdown > 0) this.countdown--;
      else { clearInterval(this.timer); this.state = 'expired'; }
    }, 1000);
  }
}
